### ISSUE TITLE
CI is broken for pull request validation

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy-website#10]
Its trying to deploy the website during validation and (very very fortunately) failing because it doesnt have permission.

We should add another configuration specifically for PR validation.

**Comment by guimcaballero** [comment]
It looks like [shalzz/zola-deploy-action](https://github.com/shalzz/zola-deploy-action) has a way to do this listed on the Readme:

> This example will build and deploy on master branch to gh-pages branch. Additionally will build only on pull requests.

This is what we're looking for right?

**Comment by cart** [comment]
Closed by #24
