### ISSUE TITLE
Bevy 0.13 typos

### ISSUE THREAD

**Issue by ramones156** [bevyengine/bevy-website#1002]
Found a few more typos while skimming through `content/news/2024-02-17-bevy-0.13/index.md` (can't make a PR so I'll put them here)

242: ~~convertion~~ conversion
301: ~~primitives shapes~~ primitive shapes
608: ~~coners~~ corners
721: ~~every~~ ever
1395: ~~encourages~~ encourages
1405: ~~enitities~~ entities
1405-1418: ~~optimizations~~ optimisations (just to keep it consistent with the article)

**Comment by ramones156** [comment]
![image](https://github.com/bevyengine/bevy-website/assets/55579979/5afe064b-2d82-4a49-a47a-b442bc17bb96)
saw this one in 1306 aswell, someone must've been tired hahah

**Comment by TrialDragon** [comment]
> ![image](https://private-user-images.githubusercontent.com/55579979/305670715-5afe064b-2d82-4a49-a47a-b442bc17bb96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMDU2NTIsIm5iZiI6MTcwODIwNTM1MiwicGF0aCI6Ii81NTU3OTk3OS8zMDU2NzA3MTUtNWFmZTA2NGItMmQ4Mi00YTQ5LWE0N2EtYjQ0MmJjMTdiYjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDIxMjkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMzU1Y2RhOWJkMWE5M2Y0NDU2ZWU2ZDE0OTE3YjQwMzBhODZhYjcwOTUwMjdkZTljNDRjNThjYTgzNGJiYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hyj8fvpHHFKRrVXSen4UOvELVAp5Lzmu7dfS7heNnwE) saw this one in 1306 aswell, someone must've been tired hahah

I believe that one isn't a typo. In various places we use `vvvvvvvvvvv` or `^^^^^^^^^^` to point things out in comments. Those are pointing arrows.

**Comment by ramones156** [comment]
Ah, that's fair (:
Might be a bit nit-picky, but having a space between the two would make it more clear
