### ISSUE TITLE
Rendering primitives example is broken

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy-website#1007]
[Originally reported on Discord.](https://discord.com/channels/691052431525675048/695741366520512563/1208541856124633221)

The [Math - Rendering Primitives](https://bevyengine.org/examples/Math/render-primitives/) example is broken, it looks like the loading bar is stuck.

<img width="1552" alt="image" src="https://github.com/bevyengine/bevy-website/assets/59022059/f21cd756-fd38-48dd-a038-734f4a4a2d7d">

```diff
- Loading module from “https://bevy-webgl2-examples.pages.dev/Math/render-primitives/wasm_example.js” was blocked because of a disallowed MIME type (“”). render-primitives
- Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://bevy-webgl2-examples.pages.dev/Math/render-primitives/wasm_example.js. (Reason: CORS request did not succeed). Status code: (null).
+ Module source URI is not allowed in this document: “https://bevy-webgl2-examples.pages.dev/Math/render-primitives/wasm_example.js”. render-primitives:929:23
```

---

<details>
  <summary>Ignore this, this was just an issue on my side</summary>

Additionally when building the website locally, I get this error:

```shell
$ zola serve
Error: Failed to serve the site
Error: Failed to render page 'bevy-website/content/examples/content/Math/render-primitives/index.md'
Error: Reason: Failed to render 'example.html'
Error: Reason: Function call 'load_data' failed
Error: Reason: `load_data`: bevy-website/content/examples/Math/render-primitives/render_primitives.rs doesn't exist
```

Note that this is after `generate_wasm_examples.sh` is run.
</details>

**Comment by TrialDragon** [comment]
Hmm, last changes to touch the examples tool was https://github.com/bevyengine/bevy-website/commit/d17be0dafb1b322a0c2a4ca0029ed65864b2fa66 and https://github.com/bevyengine/bevy-website/commit/187847d0ce11a91e01bd8beab3a0b5e416401f33 . I'm going to test it on an earlier commit to see if it's broken there just in case. Also I'll run main on local to double check it also happens on my system.

**Comment by TrialDragon** [comment]
Spontaneously started working again; safe to close issue.

**Comment by BD103** [comment]
Adding this here for the future: I believe this was fixed after [this job](https://github.com/bevyengine/bevy-website/actions/runs/7944120451) ran, which finished 10 minutes before Trial commented that zhe could no longer reproduce the issue.

[More context on Discord](https://discord.com/channels/691052431525675048/695741366520512563/1255005650749100122)
