### ISSUE TITLE
Investigate  David Lattimore's compile speed tips

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1020]
[Article](https://davidlattimore.github.io/working-on-rust-iteration-time.html). Figure out which once work well, then update the advice to include them!

- [x] Faster linker: already done
- [ ] Don't link debug info
- [ ] Build a non-relocatable executable

**Comment by AxiomaticSemantics** [comment]
I often do the `strip = "debuginfo"` thing unless actually debugging, would advise. I'm going to try the non-PIC build, that should indeed be a huge boon.

**Comment by AxiomaticSemantics** [comment]
The static link to musl may help some users, but various packages break in my environment, bevy_audio will not build here, didn't try further.
