### ISSUE TITLE
Migration Guide 0.13 - Texture Atlas rework migration unclear

### ISSUE THREAD

**Issue by GitGhillie** [bevyengine/bevy-website#1025]
Looking at the [sprite_sheet](https://github.com/bevyengine/bevy/blob/release-0.12.1/examples/2d/sprite_sheet.rs) example if you were using `TextureAtlasSprite` in a query it's currently not immediately obvious how to migrate that from the [migration guide](https://bevyengine.org/learn/migration-guides/0-12-to-0-13/#texture-atlas-rework).

One person (bless them) ran into this so there are probably more people out there running into it. For more context:
https://discord.com/channels/691052431525675048/1209175742081142836/1209175742081142836

Additionally you have `atlas_handle` in the code shown in the guide, but it's unclear what it is or where it came from.

Since I haven't worked with Bevy 2D stuff yet I'm a bit hesitant to make a PR myself.

**Comment by rparrett** [comment]
I had some ideas here:

https://gist.github.com/rparrett/508035fa19d3324db0adf8e509e7affd#httpsgithubcombevyenginebevypull10099

Was hoping to flesh that out a bit more, but haven't gotten around to it.

I also found this change quite awkward to migrate from, as I was previously using the loader from `bevy_asset_loader`, which now only loads the "layout" part. Though that's not really a Bevy problem.
