### ISSUE TITLE
0.13 migration: `Name` serialization section is incorrect

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy-website#1030]
https://bevyengine.org/learn/migration-guides/0-12-to-0-13/#fix-reflected-serialization-deserialization-on-name-component

Following the current advice would produce a broken scene.

I'm not totally sure what's going on here. This needs more investigation. It might be a bug in Bevy.

What the guide tells you to do:
```
"bevy_core::name::Name": "My Entity Name",
```

What actually works (same as in 0.12, as far as my testing shows, and as reported on [discord](https://discord.com/channels/691052431525675048/1019697973933899910/threads/1209244908372627507)):
```
"bevy_core::name::Name": (
  hash: 15171155951088048606,
  name: "My Entity Name",
),
```
Or this also works fine.
```
"bevy_core::name::Name": (
  name: "My Entity Name",
),
```

**Comment by TrialDragon** [comment]
Looking into this superficially it definitely feels like it could be a Bevy bug / code not doing what the author thought it would. I don't know enough regarding serde and Bevy's reflection to confirm or prove tho.

**Comment by TrialDragon** [comment]
Tho, if the original still works does that mean this migration guide is even necessary any more? At that point nothing has changed effectively.

**Comment by alice-i-cecile** [comment]
Yeah, we should be able to just remove the section. We should still try and figure out what happened to the change though.

**Comment by rparrett** [comment]
Okay. Can always add it back if it turns out to be

- A bug
- That is a candidate for 0.13.1

But I'm guessing we wouldn't break scenes in a point release even if "they were supposed to be broken" ?
