### ISSUE TITLE
Reversed navigation order in quick-start docs

### ISSUE THREAD

**Issue by TomaszDomagala** [bevyengine/bevy-website#1055]
Hello, it appears that the navigation order is reversed in the [quick start documentation](https://bevyengine.org/learn/quick-start/getting-started/apps/). This might be related to [this recently merged PR](https://github.com/bevyengine/bevy-website/pull/962).

![image](https://github.com/bevyengine/bevy-website/assets/25331622/dccc4b75-a3fb-417a-bf94-823c25baada8)

**Comment by TrialDragon** [comment]
I messed up, sorry. This should hopefully be fixed within the day. Thank you for reporting this!
