### ISSUE TITLE
Reduce `generate-assets` duration

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy-website#1066]
> I would be more interested in reducing the duration of each job. here, the longest one is `generate-assets`, because it's querying for fresh data every time even though it probably doesn't make sense to do it on a code change in the website.
>
> Instead of querying crates.io db / GitHub each time, we could handle a cache in the repo, and only query the external sources when the cache is not present. then have a daily job to refresh the cache

_Originally posted by @mockersf in https://github.com/bevyengine/bevy-website/issues/1061#issuecomment-1970050641_

**Comment by mockersf** [comment]
updating the cache could be done in https://github.com/bevyengine/bevy-website/blob/main/.github/workflows/deploy.yml, that way deploying the website from main would use fresh data, but working on a PR would use the cache
