### ISSUE TITLE
Delete leftover branches

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy-website#1086]
This repository has [a few branches](https://github.com/bevyengine/bevy-website/branches/all) that were leftover by maintainers and Bors. Since they are all stale, they can probably be deleted.

- `alice-i-cecile-path-*`
  - All of these PRs have been merged or closed.
- `create-pull-request/patch-8favc9d`
  - This PR has been merged in #1023, originally created by Github Actions.
- `0.13-blog`
  - This PR has been merged in #891. Bevy 0.13 is released!
- `staging` and `trying`
  - Leftover from when we used Bors.

As far as I am aware, there are only two branches that are actually necessary: `main` and `gh-pages`. Please--uh--don't delete these ones. XD

<img width="1552" alt="image" src="https://github.com/bevyengine/bevy-website/assets/59022059/ad23c10b-cf75-4cc3-806c-6033f8846470">

Related issue on Bevy main: https://github.com/bevyengine/bevy/issues/11655

**Comment by alice-i-cecile** [comment]
![image](https://github.com/bevyengine/bevy-website/assets/3579909/8aa4b805-147b-441a-a470-80aaaa9e526f)

Done!

**Comment by BD103** [comment]
That was fast! Thank you :)
