### ISSUE TITLE
Improve speed of `mega-linter`

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy-website#1087]
`mega-linter` is a tool that we use to check all HTML, Markdown, and Sass files. It currently takes around 3 minutes to run, which is the longest of the 5 initial lint jobs. Since it is run first, it blocks the `generate-*` and `build-website` jobs from starting. Increasing the speed of `mega-linter` would increase the speed of the entire CI.

The slowest part of using `mega-linter` is not running it, but instead downloading it. It requires downloading a 3.5 GB docker image, which contains a whole host of unused linters.

`mega-linter` allows using custom [flavors](https://megalinter.io/latest/flavors/), which are slim versions of the default image. If the CI could be configured to use one of those flavors instead, the CI times would be decreased. We currently only use 3 linters, so only they are required:

https://github.com/bevyengine/bevy-website/blob/cbd158c930dcb524b1992a34682deec19bcc1c63/.mega-linter.yml#L1-L4

I additionally [asked in Github Discussions](https://github.com/oxsecurity/megalinter/discussions/3412) how to create a custom flavor of `mega-linter` that just includes the linters we need. If that's not possible and a provided flavor is not found, it may be worth just installing each linter manually.

**Comment by TrialDragon** [comment]
If making our own custom flavor isn't worth it, then I think https://megalinter.io/latest/flavors/javascript/ should work fine. It contains all the things that I think we would use. But like you said manually installing is also viable given how few there is right now.

**Comment by BD103** [comment]
Ok, then I can see this going in two steps:

1. Switch the current flavor to Javascript, which should decrease the download size to ~800 MB.
2. If it's still too slow (I'm thinking >30 seconds), then we can try creating our own flavor.
   - Someone [respond](https://github.com/oxsecurity/megalinter/discussions/3412#discussioncomment-8733416) to my question with good information on how to create a custom flavor.

I'm going to mark this as good first issue so someone can try item 1.

**Comment by BD103** [comment]
With #1090 merging, I don't think we need to create a custom flavor. The Javascript one speeds up `mega-linter` enough for now that it's not worth the effort of maintaining a fork.
