### ISSUE TITLE
Redirect from or de-index Book pages until ready for public consumption

### ISSUE THREAD

**Issue by zrisher** [bevyengine/bevy-website#1088]
Hi there! I have never used Zola before, and am new to Bevy, so I apologize if I missed anything looking into this.

## The Problem

When a user searches ["bevy getting started"](https://www.google.com/search?q=bevy+getting+started) on Google, which I assume is fairly common, they are presented with two official-looking results:

![image](https://github.com/bevyengine/bevy-website/assets/1958130/79d58e77-b3b4-4425-ac00-d3e7ef6c56dc)

The first result is from the Book (`/learn/book/getting-started/`), which presents a blank-looking page with the message "This page is hidden because an ancestor is hidden."

![image](https://github.com/bevyengine/bevy-website/assets/1958130/84f07caa-012c-4dc0-9171-9236ac3b19b1)

The second result (`/learn/quick-start/getting-started/`) provides the content a user is probably looking for.

## Detail
As I understand it from #623, it was intended that the Book pages would not be indexed by search engines until they were more complete. Unfortunately, using `status = 'hidden'` on the content pages does not seem to accomplish this.

## The Solution

The solutions I see, until these pages are ready for public consumption, are to either:
1. Redirect from each of the book pages to some other location, e.g. `redirect_to = '/learn/'`. This would have the disadvantage of requiring anyone working on these pages locally to temporarily remove the redirect.
2. [Temporarily hiding these pages from results](https://support.google.com/webmasters/answer/9689846?sjid=11127847331212107266-NC) using google webmaster tools. This would be a bit more work, and per their documentation would last "only about six months."

I'm happy to create a PR for solution 1, if that's the route you'd like to go.

**Comment by TrialDragon** [comment]
This is only a single page of the book visible, and that's because it's aliased to the quick start guide's version for migration / redirection reasons, but it seems stuff isn't working, so it's not redirecting to the correct page like it's supposed to. For a quick fix `/learn/book/getting-started/_index.md` should be set to redirect to `/learn/quick-start/getting-started` since the alias stopped working (I want to say it used to tho).

We already went thru the tango of getting all the books pages de-indexed, and luckily they are.

**Comment by zrisher** [comment]
> the alias stopped working (I want to say it used to tho)

Looking through [zola/components/site/src/lib.rs](https://github.com/getzola/zola/blob/11d2521d7a044501a3bbbb469137b7d4f771b0b8/components/site/src/lib.rs#L859), it seems like the aliases option makes Zola create a new redirection page at the aliased location, which must be failing because content already exists for that route. I tried:
* removing `content/learn/book/getting-started/_index.md`
* then navigating to `/learn/book/getting-started`

and it does indeed redirect me to `/learn/quick-start/getting-started`. 

(Which is a bit surprising, since the alias is for `/learn/book/quick-start` and not `/learn/book/getting-started`, but maybe non-existant paths resolve to the closest index, and `content/learn/book/_index.md` redirects there.)

In any case, since this content **should** exist, removing it is not an option, so I'll prepare a PR that adds the redirect to the book page.
