### ISSUE TITLE
Re-add Meetkai to Past Sponsors

### ISSUE THREAD

**Issue by TrialDragon** [bevyengine/bevy-website#1098]
In 128461a it seems that the Past Sponsor Meetkai was removed and not re-added during the changes. I can't find them anywhere as a present sponsor, so I presume they're still a Past Sponsor and should still be in that list.

**Comment by alice-i-cecile** [comment]
Yep, they should be there under Past Sponsors :)

**Comment by TrialDragon** [comment]
@alice-i-cecile any idea who they were sponsoring and for how much?

**Comment by alice-i-cecile** [comment]
I believe it was @cart.

**Comment by BD103** [comment]
Once Cart responds with the sponsor details, this needs to be added to `individual-sponsors.toml`:

```toml
[[sponsor]]
past = true
name = "Meetkai"
recipient ="cart"
amount = ?
```

**Comment by cart** [comment]
It was $1,000 a month. Just put out a PR to fix this!
