### ISSUE TITLE
Group `hide-lines` checked files together in CI

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy-website#1100]
> somewhat unrelated, but that CI log that failed should probably have a quiet mode or something because at first I thought all files were having an issue instead of a single file
>
> @IceSentry on [Discord](https://discord.com/channels/691052431525675048/695741366520512563/1216820769229897818)

You can group log lines together in Github Actions using [workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions).

**Comment by rparrett** [comment]
Could you link to the workflow run that motivated this issue?

**Comment by BD103** [comment]
> Could you link to the workflow run that motivated this issue?

It's likely [this one](https://github.com/bevyengine/bevy-website/actions/runs/8238153951/job/22528457171). I'm drafting a fix now.
