### ISSUE TITLE
Automatically update sponsorship data

### ISSUE THREAD

**Issue by TimJentzsch** [bevyengine/bevy-website#1102]
We are displaying the current monthly donation amount, as well as the number of active individual and corporate sponsors on the [donation page](https://bevyengine.org/donate/):
![Donation stats on the website](https://github.com/bevyengine/bevy-website/assets/13908946/6830fdad-de9f-49e3-9f1d-863fdab2ce40)

Updating this manually will not be a feasible long-term strategy, so we should automate it.

We can probably use the ["List subscriptions" endpoint](https://docs.stripe.com/api/subscriptions/list) from Stripe to get the data we need.
There is also a [`stripe`](https://docs.rs/stripe-rust/latest/stripe/) crate which might help us.

The potential workflow could be:

- Create a Rust script which takes a Stripe API key as input and returns the data we need in a TOML file. See `/content/donations/foundation-sponsors.toml` for the format we need. We should probably figure out how exactly we want to present this data; e.g. if the sponsors without name should just be aggregated as numbers instead of including them in the TOML file.
- Use the data in the template of the donation page. If we do not change the format, we may not need to do anything here.
- Re-generate and re-deploy the page regularly, e.g. daily.

**Comment by TimJentzsch** [comment]
One other complication could be the images, as they are not available via Stripe, but added manually. So perhaps we need to have a separate file where they are defined to avoid them being overwritten.

**Comment by alice-i-cecile** [comment]
@cart has been chewing on how to automate this as well :)

**Comment by TrialDragon** [comment]
Mm, for images, we could have the format be something like having a sponsors folder in static assets and having the files be lowercase underscore versions of names gotten via the api. We could have some part of the workflow that runs on deploy and checks if there is an image for all the sponsors that should, if not make an issue for that image if one doesn't exist already. So it's still manual in the sense that someone needs to resolve the issue by adding the images in PR before the site can deploy again.

When I say deploy, I mean deploy. I don't think regular ci should be blocked by a missing sponsor image.

**Comment by TrialDragon** [comment]
As for the rest, it could just be a `generate-donations` CI tool like community or errors. The site already regenerates daily regardless of the situation.

**Comment by cart** [comment]
Planning on picking this up today. My general strategy will be to:

1. Create a new `bevy-donors` repo 
2. Create a cli tool to:
  a. Query Stripe for all present and past sponsorship information. This _might_ contain name / link info, if the sponsor chose to include it.
  b. Join that with manually provided "override"  toml for logos / links / names / etc (checked into the bevy-donors repo)
  c. Export the final `foundation-sponsors.toml` as a release, which the bevy-website repo can consume

**Comment by BD103** [comment]
Closed in #1116!
