### ISSUE TITLE
Performance broken in examples on focus change

### ISSUE THREAD

**Issue by mochou-p** [bevyengine/bevy-website#1115]
Tested on the breakout example (https://bevyengine.org/examples/Games/breakout/)

The game is smooth and multithreaded from the start, but when the `<canvas>` loses and regains focus, the game becomes very laggy for what it is. After the focus change, only one thread at a time does all the work, and it is really struggling. (AMD Ryzen 5 2600)

![image](https://github.com/bevyengine/bevy-website/assets/66534926/37e5fb29-2bbe-44a1-a0f5-2872d56969d1)

**Comment by alice-i-cecile** [comment]
Duplicate of https://github.com/bevyengine/bevy/issues/12126: should be fixed in 0.13.1 :) We'll double-check once that's released and the site is updated.

Thanks for reporting this though: the graph is particularly lovely.
