### ISSUE TITLE
Clarify VS2019 toolchain advice in Setup

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#112]
Currently, the setup guide tells Windows users to:

> Windows: Make sure to install VS2019 build tools

But following the link and downloading the executable presents them with a baffling (to novice programmers) array of tools to consider. I believe the C++ bundle is what's needed, but that's not at all intuitive, considering we're writing in Rust ;)

**Comment by TrialDragon** [comment]
This appears to have been fixed by https://github.com/bevyengine/bevy-website/pull/621 in https://github.com/bevyengine/bevy-website/commit/ff852da92ea46caafad96335d005ae3f3fe5ba6a.
