### ISSUE TITLE
Example Assets: 404 not found

### ISSUE THREAD

**Issue by lomirus** [bevyengine/bevy-website#1128]
In the console of  [Transmission Example](https://bevyengine.org/examples/3D%20Rendering/transmission/), it says:
```
GET https://bevyengine.org/assets/examples/environment_maps/pisa_diffuse_rgb9e5_zstd.ktx2.meta 404 (Not Found)
```

![image](https://github.com/bevyengine/bevy-website/assets/21173956/58915436-d44b-4e08-af91-0e36ca552ca2)

**Comment by rparrett** [comment]
It is normal for meta files to not necessarily exist.

This **shouldn't** cause the loading bar to get stuck, but there may be a separate issue there. #1119.
