### ISSUE TITLE
`bevyengine.org` should not hold a CNAME record as an apex domain

### ISSUE THREAD

**Issue by Kritzefitz** [bevyengine/bevy-website#1143]
The website's domain name `bevyengine.org` is, speaking in DNS terms, an apex domain, which means it must hold `NS` record to specify which nameservers are responsible for this zone. However, `bevyengine.org` also contains a `CNAME` record pointing to `bevyengine.github.io`. This isn't allowed in DNS, because RFC 2181 specifies in section 10.1:

> An alias name (label of a CNAME record) may, if DNSSEC is in use, have SIG, NXT, and KEY RRs, but may have no other data.

On a more practical level, having a `CNAME` record on an apex domain will confuse some DNS resolvers, because during their search for the `NS` records or other types of records usually found on apex domains (such as `DS` records used for DNSSEC) they might stumble across the `CNAME` record and redirect their original search for the `NS` (or `DS`) record to the domain specified by the `CNAME`. This makes it impossible to resolve `bevyengine.org` with some DNS resolvers, for example, systemd-resolved will currently fail to resolve `bevyengine.org` if DNSSEC validation is enabled:

```
$ query bevyengine.org
bevyengine.org: resolve call failed: DNSSEC validation failed: no-signature
```

The [GitHub documentation on how to add a custom domain to GitHub pages](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) also doesn't recommend using a `CNAME` on an apex domain. Instead it recommends to use a list of `A` and `AAAA` records directly (or something like an `ALIAS` directive, if supported by your DNS server).

**Comment by cart** [comment]
Should be fixed now. Thanks for the heads up!
