### ISSUE TITLE
Example in the Resources section of the Bevy Book doesn't work

### ISSUE THREAD

**Issue by ddxt** [bevyengine/bevy-website#119]
In the final section of the Bevy Book, the example for setting up a timer resource doesn't work. The "greet_people" system produces the following error:

no method named `tick` found for struct `bevy::prelude::ResMut<'_, GreetTimer>` in the current scope
items from traits can only be used if the trait is implemented and in scope

HelloPlugin also still uses the add_resource function, which was renamed to insert_resource in 0.5.

**Comment by adoa** [comment]
I just went over this example, too, and realized that you have to change
`    if timer.tick(time.delta()).just_finished() {`
into
`    if timer.0.tick(time.delta()).just_finished() {`

because the datatype `GreetTimer` was defined as
`struct GreetTimer(Timer);`

**Comment by TrialDragon** [comment]
This was fixed in https://github.com/bevyengine/bevy-website/commit/decfd3317f4df83a24d3ed28a3db8cd02f056718 . This issue can be closed.
