### ISSUE TITLE
`release-notes` CLI option should try its best to list authors

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1192]
Scraping the authors of the commits would go a long way to automating this process. See https://github.com/bevyengine/bevy-website/pull/1191 to see the current results.

Part of #1163.

**Comment by IceSentry** [comment]
Right, I had that at some point, but I removed it because getting the list of authors is really slow and was slowing me down while iterating. Now that it's ready I could add it back. Should be pretty easy I think.
