### ISSUE TITLE
`release-notes` CLI tool should link to the original PR

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1193]
This should be linked in the body of the text. This is extremely helpful as a time save for writers: the link should often be included in the body of the text, and it saves us from having to look up the link to each PR ourselves.

Part of Part of https://github.com/bevyengine/bevy-website/issues/1163.

**Comment by IceSentry** [comment]
I didn't link the PR because the previous release didn't include any links, but it would be pretty easy to add. Maybe just as a comment at the top of the generated files.
