### ISSUE TITLE
Automatically generate issues for each uncompleted release note

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1220]
Two of the largest remaining challenges involved in #1163 are:

1. Prompting feature authors to write release notes for the corresponding sections.
2. Keeping track of what release note sections still need to be written, especially as more sections are completed.

[Previously](https://github.com/bevyengine/bevy-website/pull/891#issuecomment-1914655314), this was done by manual suggestions and tracking. This is a) a lot of work to generate and b) generates an endless stream of notifications for everyone involved.

There are two proposals for how we could handle and automate this.

# Proposal 1: big tracking issue

As part of a tracking issue for the release (e.g. #1188), we could generate a checkbox list like before, suggesting that all of the authors listed on the PR handle the process.

## Advantages

- no new issues generated.

## Disadvantages

- everyone gets pinged for every update
- the thread gets very long as people chime in to claim issues
- only 50 people can be pinged in a single comment
- only maintainers and the comment author can update the status of each ticket
- discoverability is poor
- doesn't work terribly well when done on a continual basis: we need to make the tracking issue for the next release immediately and constantly edit it?

# Proposal 2: a million issues

Instead, for each release note entry generated (aka each merged PR with a `C-Needs-Release-Note` entry, a bot makes an issue with a  "Write release notes for PR TITLE" with a link to the PR and pings the authors. This issue is added to the milestone.

## Advantages

- discussions are separated, and thus much less noisy
- much easier to discover work that needs to be done
- PRs can say "Closes #X" or the triage team can update this and it will work great without maintainer intervention
- we can add advice on how to write release notes to every issue
- issues can be generated dynamically as PRs are merged throughout the cycle

## Disadvantages

- makes a large number of issues! This will be noisy for 0.14 due to the last-minute nature of the work
- need to figure out more complex bot workflows to write this tool

**Comment by alice-i-cecile** [comment]
I pretty strongly prefer proposal 2: I think this is the way to go.

**Comment by MrGVSV** [comment]
I think I also favor Proposal 2. It will be a bit noisy, but it's not like every PR will be tagged with `C-Needs-Release-Note` (although, I'd be excited to see that release post lol).

But I agree it will be much more contributor-friendly. Authors know exactly where their help may be needed, even if they choose not to write the release note themselves. It makes it easier for others to find and pick up work. It will be easier to track across an entire release cycle, whereas things might get lost in a single long-lived issue. And it's hopefully less work for the maintainers.
