### ISSUE TITLE
Write release notes for PR #13501: Implement Rhombus 2D primitive.

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1226]
https://github.com/bevyengine/bevy/pull/13501 needs release notes for the upcoming Bevy release!

Original authors: @salvadorcarvalhinho, @LuisFigueiredo73

Please reply below if you'd like to write these notes. 
While the author(s) of the PR often have the context, knowledge and motivation to draft the release notes for their feature,
anyone can contribute release notes!

------

Release notes should:

1. Clearly motivate the change.
2. Be written in a way that is understandable by the average Bevy user: some programming background and a general understanding of games.
3. Show off the coolest features of the PR. Screenshots are awesome, but elegant APIs are also welcome!
4. If this was a perf-centric PR, quantify the performance improvements. Graphs and statistics work well for this.

We can help you revise the release notes: a rough draft alone is incredibly useful :)
Your expertise is invaluable for contextualizing the changes; we'll work with you to bring the technical writing up to par.

To submit your release notes, modify `..\release-content\0.14\release-notes\13501_Implement_Rhombus_2D_primitive.md` and submit a PR.
In that PR, please mention this issue with the `Fixes #ISSUE_NUMBER` keyphrase so it gets closed automatically.

**Comment by alice-i-cecile** [comment]
This section should tackle all of the new shapes that we've added: 3D triangles, rhombuses, circles...

**Comment by Chubercik** [comment]
> This section should tackle all of the new shapes that we've added: 3D triangles, rhombuses, circles...

In this case, release notes should be (in my opinion) prepared as a continuation of the [Primitive Shapes](https://bevyengine.org/news/bevy-0-13/#primitive-shapes) section of the Bevy 0.13 announcement post:

- mention of the state primitives shapes were in 0.13,
- what was added, and the motivation behind these additions (collectively preferred over individually),
- what is yet to be (or is hoped to be) added in the future.
