### ISSUE TITLE
Write release notes for PR #12889: Implement GPU frustum culling.

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1307]
https://github.com/bevyengine/bevy/pull/12889 needs release notes for the upcoming Bevy release!

Please reply below if you'd like to write these notes. 
While the author(s) of the PR often have the context, knowledge and motivation to draft the release notes for their feature, anyone can contribute release notes!

------

Release notes should:

1. Clearly motivate the change.
2. Be written in a way that is understandable by the average Bevy user: some programming background and a general understanding of games.
3. Show off the coolest features of the PR. Screenshots are awesome, but elegant APIs are also welcome!
4. If this was a perf-centric PR, quantify the performance improvements. Graphs and statistics work well for this.

We can help you revise the release notes: a rough draft alone is incredibly useful :)
Your expertise is invaluable for contextualizing the changes; we'll work with you to bring the technical writing up to par.

To submit your release notes, modify `..\release-content\0.14\release-notes\12889_Implement_GPU_frustum_culling.md` and submit a PR.
In that PR, please mention this issue with the `Fixes #ISSUE_NUMBER` keyphrase so it gets closed automatically.

**Comment by jgayfer** [comment]
Took a stab at this in https://github.com/bevyengine/bevy-website/pull/1439.

I need a hand on motivating the change, but (I think) the bones are there.

**Comment by zhaop** [comment]
I suspect this is the wrong place to write this (and it looks like I'm late as it's already merged), but I'm new here and wasn't sure where this is supposed to go :)

I'm upgrading the transform-gizmo crate to 0.14.0-rc and noticed that [Bevy #12889](https://github.com/bevyengine/bevy/pull/12889/) changed the `dynamic_offset: Option<NonMaxU32>` field to `extra_index: PhaseItemExtraIndex` for a number of structs:

`AlphaMask3d`, `AlphaMask3dDeferred`, `AlphaMask3dPrepass`, `Opaque2d`, `Opaque3dDeferred`, `Opaque3dPrepass`, `Shadow`, `Transmissive3d`, `Transparent2d`, `Transparent3d`, `TransparentUi`

This seems like a breaking change (see e.g. [bevy_ecs_tilemap](https://github.com/ChristopherBiscardi/bevy_ecs_tilemap/commit/29f5818e86ddd4b52744426ab5f5154a8951d7d5)'s change) so it's probably a good idea to have this in the migration notes somewhere? As a draft suggestion:

> The `dynamic_offset: Option<NonMaxU32>` field for phase items is now `extra_index: PhaseItemExtraIndex`, which wraps a u32. Instead of `None`, use `PhaseItemExtraIndex::NONE`. This change affects `AlphaMask3d`, `AlphaMask3dDeferred`, `AlphaMask3dPrepass`, `Opaque2d`, `Opaque3dDeferred`, `Opaque3dPrepass`, `Shadow`, `Transmissive3d`, `Transparent2d`, `Transparent3d`, and `TransparentUi`.
