### ISSUE TITLE
Write release notes for PR #13199: Add BufferVec, an higher-performance alternative to StorageBuffer, and make GpuArrayBuffer use it.

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1310]
https://github.com/bevyengine/bevy/pull/13199 needs release notes for the upcoming Bevy release!

Please reply below if you'd like to write these notes. 
While the author(s) of the PR often have the context, knowledge and motivation to draft the release notes for their feature, anyone can contribute release notes!

------

Release notes should:

1. Clearly motivate the change.
2. Be written in a way that is understandable by the average Bevy user: some programming background and a general understanding of games.
3. Show off the coolest features of the PR. Screenshots are awesome, but elegant APIs are also welcome!
4. If this was a perf-centric PR, quantify the performance improvements. Graphs and statistics work well for this.

We can help you revise the release notes: a rough draft alone is incredibly useful :)
Your expertise is invaluable for contextualizing the changes; we'll work with you to bring the technical writing up to par.

To submit your release notes, modify `..\release-content\0.14\release-notes\13199_Add_BufferVec_an_higherperformance_alternative_to_StorageB.md` and submit a PR.
In that PR, please mention this issue with the `Fixes #ISSUE_NUMBER` keyphrase so it gets closed automatically.

**Comment by djeedai** [comment]
@alice-i-cecile  Why is this completed? Where's the release note? The PR doesn't explain anything about the new data structure, and I have no idea how to update Hanabi, whether I should just rename to `RawBufferVec` or try to use the new `BufferVec`? We can't have migration notes say "there's a new more performant data structure" and not explain anything about it :(

**Comment by alice-i-cecile** [comment]
Sorry, this should have been closed as "won't fix": rendering folks don't think this is valuable enough to cover in the release notes.
