### ISSUE TITLE
Merging multiple PRs into a single release note is unintuitive and clunky

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1354]
Many large features (or areas of related work) end up being done over multiple distinct PRs. When triaging, it's not uncommon for multiple of them to get the `S-Needs-Release-Note` label. However in the final document, we want to group them under a single heading.

If we simply delete one of the entries, rerunning the tool to catch new updates will add back the old merged PRs!

The current workflow is:
1. Delete the file and entry used for the PR(s) you're merging in.
2. Remove the entry from the `_release-notes.toml` file.
3. Edit the file for the PRs you're reusing (without changing the file name)
4. Remove the S-Needs-Release-Note label from the PR(s) that have been  merged in so they don't get regenerated

**Comment by alice-i-cecile** [comment]
I think the best way to do this is to add a set of PR numbers to the metadata for each release note entry, explaining which PR they cover. I expect this work could be nicely tackled alongside #1350, as they both touch on the question of 'when should we regenerate notes".

**Comment by TrialDragon** [comment]
Presuming no one else who has more time wants to tackle this, I'll work on this.

**Comment by alice-i-cecile** [comment]
That would be incredibly valuable. Let me know if I can do anything to support you in this.
