### ISSUE TITLE
Mention RFCs in Contributing section of the book

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#136]
See https://github.com/bevyengine/rfcs

**Comment by TrialDragon** [comment]
Where in the contributing section should RFCs be mentioned? In the Contributing page? Code or Docs page? It's own Proposals page? (Also, this is only within the context of proposing stuff, right, not as a place to look for relevant information when contributing?)

**Comment by alice-i-cecile** [comment]
I think we should close this out: this belongs in the CONTRIBUTING.md part of the Bevy repo.
