### ISSUE TITLE
The same person appears as a current sponsor and a past at the same time

### ISSUE THREAD

**Issue by YohDeadfall** [bevyengine/bevy-website#1407]
Just found an issue with `now I have to make a game with bevy` being in two lists which promotes them to another category, Schrödinger's. Jokes aside, it should be fixed and I can do that, just don't know from what list to remove them.

**Comment by mockersf** [comment]
list are auto generated from https://github.com/bevyengine/bevy-donors, there's maybe a bug in there but it's hard to find without some example data from stripe

**Comment by YohDeadfall** [comment]
Then it means that the sponsorship FAQ might be outdated:

> ### I sponsored but the metrics / names / logos on the donate page haven't updated!
>
> This _isn't automated_ (yet!). For now ... bear with us. We try to update these as quickly as possible.

From the Stripe documentation([link](https://docs.stripe.com/api/payment_intents):

> A PaymentIntent guides you through the process of collecting a payment from your customer. We recommend that you create exactly one PaymentIntent for each order or customer session in your system. You can reference the PaymentIntent later to see the history of payment attempts for a particular session.

It implies that each customer can have more than one intent while the code doesn't group them by `customer_id`. That's probably the bug. If it's okay to fix it, please assign it to me.

**Comment by YohDeadfall** [comment]
False alarm about the dup. I looked into the generated `donors.toml` and found that there are two distinct customers with a very similar name, but one of them had `well, ` in the beginning of theirs name. And since all past donors are separated by a comma, it makes it look like there's a duplicate.
