### ISSUE TITLE
Observers code in release notes is unidiomatic

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1450]
From a failure to compile on the examples, I found this chunk of code in the Observers example 

(`examples/ecs/observers.rs:93-98`)
```rust
    commands
        .spawn(Mine::random(&mut rng))
        // Observers can watch for events targeting a specific entity.
        // This will create a new observer that runs whenever the Explode event
        // is triggered for this spawned entity.
        .observe(explode_mine);
```

This seems to imply the desired functionality has already been merged? Unless I'm misunderstanding, which is definitely possible.

_Originally posted by @QueenOfSquiggles in https://github.com/bevyengine/bevy/issues/13936#issuecomment-2183336870_

**Comment by TrialDragon** [comment]
Is this resolved by #1451, or am I misunderstanding stuff.
