### ISSUE TITLE
Migration notes for GPU frustum culling need work

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1454]
I'm upgrading the transform-gizmo crate to 0.14.0-rc and noticed that [Bevy #12889](https://github.com/bevyengine/bevy/pull/12889/) changed the `dynamic_offset: Option<NonMaxU32>` field to `extra_index: PhaseItemExtraIndex` for a number of structs:

`AlphaMask3d`, `AlphaMask3dDeferred`, `AlphaMask3dPrepass`, `Opaque2d`, `Opaque3dDeferred`, `Opaque3dPrepass`, `Shadow`, `Transmissive3d`, `Transparent2d`, `Transparent3d`, `TransparentUi`

This seems like a breaking change (see e.g. [bevy_ecs_tilemap](https://github.com/ChristopherBiscardi/bevy_ecs_tilemap/commit/29f5818e86ddd4b52744426ab5f5154a8951d7d5)'s change) so it's probably a good idea to have this in the migration notes somewhere? As a draft suggestion:

> The `dynamic_offset: Option<NonMaxU32>` field for phase items is now `extra_index: PhaseItemExtraIndex`, which wraps a u32. Instead of `None`, use `PhaseItemExtraIndex::NONE`. This change affects `AlphaMask3d`, `AlphaMask3dDeferred`, `AlphaMask3dPrepass`, `Opaque2d`, `Opaque3dDeferred`, `Opaque3dPrepass`, `Shadow`, `Transmissive3d`, `Transparent2d`, `Transparent3d`, and `TransparentUi`.

_Originally posted by @zhaop in https://github.com/bevyengine/bevy-website/issues/1307#issuecomment-2186853409_

**Comment by alice-i-cecile** [comment]
I'm happy with that as a migration guide entry: please feel free to make a PR @zhaop :) I suspect we need a new entry in https://github.com/bevyengine/bevy-website/tree/main/release-content/0.14/migration-guides

**Comment by zhaop** [comment]
Ah, that's how it works. Done :) https://github.com/bevyengine/bevy-website/pull/1455

**Comment by zhaop** [comment]
Also, not sure how _guides.toml is ordered, so I just inserted my entry next to other rendering entries where it seemed to make sense.
