### ISSUE TITLE
Add link to naga bug to SSR notes

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1463]
Raised https://github.com/bevyengine/bevy-website/pull/1442#discussion_r1655483395 by @MrGVSV. Punted to follow-up to unblock editing.

Might be https://github.com/gfx-rs/wgpu/issues/4524

**Comment by alice-i-cecile** [comment]
I can't find this still. Closing as "can't fix", but feel free to submit it if you find it.

**Comment by rdrpenguin04** [comment]
That is the correct bug link, as far as I can tell; I'd say it's worth putting in
