### ISSUE TITLE
`generate-release` must be run from the `generate-release` folder

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy-website#1465]
`generate-release` assumes that it is run from the [`generate-release`](https://github.com/bevyengine/bevy-website/tree/45998c45f2b43fe770526bf268f68b7dd6f44632/generate-release) folder, so it always writes to `../release-content`. This is an issue when it is called from the root directory using `cargo run -p generate-release`, and tripped me up when I first started using the tool.

I propose that `generate-release` always switch into the correct directory, so it can keep these assumptions. If this were a shell script I'd do something like the following, but it may be more involved for Rust:

https://github.com/bevyengine/bevy-website/blob/45998c45f2b43fe770526bf268f68b7dd6f44632/generate-errors/generate_errors.sh#L3-L4

**Comment by alice-i-cecile** [comment]
This tripped me up too; we should fix this.
