### ISSUE TITLE
Authors field for release notes has too many false positives

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1468]
>  `@Alice` maybe we should default to Authors being populated by the original PR creator, then have a second (not actually rendered) list of "potential authors", populated by commit authors

- @cart

The problem here is that people who left tiny suggestions get credited by default. While people who submit fixes or do extensive design work should be credited, typo fixes don't count 😛

**Comment by doup** [comment]
In case someone wants to tackle this, as mentioned in Discord:

> first author should be the PR author, after that come the contributors… [it's a matter of splitting this](https://github.com/bevyengine/bevy-website/blob/main/generate-release/src/release_notes.rs#L69-L71) into two props in the generated TOML (change generate_metadata_block to accept these in two separate vecs). Then update the [release_notes.md](https://github.com/bevyengine/bevy-website/blob/main/templates/shortcodes/release_notes.md) template.
