### ISSUE TITLE
Meshlet screenshot should have no window decorations

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy-website#1474]
![image](https://github.com/bevyengine/bevy-website/assets/9047632/ff503e10-ab8d-4308-8f17-485e253ce45e)

**Comment by BD103** [comment]
The image in question is [here](https://github.com/bevyengine/bevy-website/blob/7cb0016ebccef973d48edb2b5ac8f8b196058f92/content/news/draft-bevy-0.14/meshlets.png).

**Comment by JMS55** [comment]
I actually wanted to record a small video showing the clusters changing as you move the camera around. Also need to add zeux to the list of contributors.
