### ISSUE TITLE
Missing link to "better scenes" document under  what´s next?

### ISSUE THREAD

**Issue by TotalKrill** [bevyengine/bevy-website#1502]
in this file: content/news/draft-bevy-0.14/index.md

link is missing

Better scenes: Scenes are one of Bevy's core building blocks: designed to be a powerful tool for saving games, authoring levels and creating reusable game objects, whether they're a radio button widget or a monster. More features and a unified syntax between assets and code should unblock progress on a UI widget abstraction, tools less boilerplates. Check out the [design doc](http://127.0.0.1:1111/news/draft-bevy-0-14/TODO) for more information.

**Comment by alice-i-cecile** [comment]
Fixed in #1506. I was hoping to get a more up-to-date design doc in place, but it wasn't ready in time!
