### ISSUE TITLE
Automatically run pngcrush on example screenshots

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy-website#1534]
> It would be good to run `pngcrush` or another image optimization tool on these, before it gets merged.

I crushed it manually for this time, we could update the action to do it automatically for next.

_Originally posted by @mockersf in https://github.com/bevyengine/bevy-website/pull/1530#issuecomment-2209547149_

**Comment by ilyvion** [comment]
Consider using [oxipng](<https://crates.io/crates/oxipng>), if for no other reason than that it's written in Rust. (/s) I'm kidding, it's both fast and produces good results!
