### ISSUE TITLE
Migration guide: Missing Plane3d -> InfinitePlane3d

### ISSUE THREAD

**Issue by jf908** [bevyengine/bevy-website#1536]
In this PR https://github.com/bevyengine/bevy/pull/12426, the Plane3d type was renamed to InfinitePlane3d and Plane3d became a type for finite planes so it now has an extra constructor parameter for size.

I think this counts as a breaking change and should be included in the 0.13->0.14 migration notes?

**Comment by andristarr** [comment]
I guess this will need to be done by the maintainers? As the automation to pick up migration guide notes from a PR is ran when the PR is being merged
