### ISSUE TITLE
Migration guide corrections

### ISSUE THREAD

**Issue by ilyvion** [bevyengine/bevy-website#1540]
The signature of the function you need to pass to `App::set_runner` has changed and this isn't mentioned at all in the migration guide.

Also, the section "Separate states from core ECS" states
> Projects that use `bevy_app` directly and use states will need to add the `bevy_state` feature.

but `bevy_app` has no such feature. I think maybe you meant "that use `bevy` directly?" (It has a feature with that name)

**Comment by BD103** [comment]
Thanks for the report! I think the signature likely changed in the `AppExit` PR, but I'll need to go through the blame to confirm.

As for the second bit, I actually just fixed it yesterday in #1539! :)

**Comment by alice-i-cecile** [comment]
`App::set_runner` changes will be due to https://github.com/bevyengine/bevy/pull/9202

**Comment by BD103** [comment]
> `App::set_runner` changes will be due to [bevyengine/bevy#9202](https://github.com/bevyengine/bevy/pull/9202)

It also appears that https://github.com/bevyengine/bevy/pull/13022 contributed to the breaking change as well. I'm working on a PR for this now.
