### ISSUE TITLE
A broken URL which lead to a 404 in the quick-start learn page.

### ISSUE THREAD

**Issue by olvior** [bevyengine/bevy-website#1549]
In the learn page, https://bevyengine.org/learn/quick-start/introduction/, there is a broken link.
The link leads to https://bevyengine.org/learn/quick-start/contributing which just leads to a 404 page not found.
The hyperlink's text is: "[built in the open by volunteers](https://bevyengine.org/learn/quick-start/contributing)" in the "What's a Bevy" section.

**Comment by TrialDragon** [comment]
Ah, shoot. That should go to `https://github.com/bevyengine/bevy-website/blob/main/CONTRIBUTING.md` then eventually `https://bevyengine.org/contributing/` once the proper contributing book is done.

**Comment by TrialDragon** [comment]
> Should this link to https://bevyengine.org/contributing/introduction now?

Yes, it should, and it already does. (The link on the live site is to that page).
