### ISSUE TITLE
Examples link to old URL, causing multiple redirects

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy-website#1558]
The links for individual examples on this page: https://bevyengine.org/examples/ link to e.g.
```
https://bevyengine.org/examples/2D%20Rendering/2d-shapes
```
Because the links don't have trailing slashes, the user then gets redirected via an http 301 to
```
https://bevyengine.org/examples/2D%20Rendering/2d-shapes/
```
Which loads as a zola redirect page that does a "meta refresh redirect" to
```
https://bevyengine.org/examples/2d-rendering/2d-shapes/
```

We should fix the links so that they send the user straight to the correct URL.

**Comment by TrialDragon** [comment]
Okay, so turns out I missed stuff when I did https://github.com/bevyengine/bevy/pull/12348; didn't change the category names to kebab case, and I guess I need to add a trailing forward slash to avoid a http 301. I need to go and make a new PR on the main Bevy repo to resolve this.

**Comment by TrialDragon** [comment]
Now that this is fixed, we probably won't see the results on the live site until the next update, probably 1.14.1, since the examples, and example-showcase I believe, use the latest GitHub.  (Marking this here in case someone thinks it isn't fixed still prior to the next version).
