### ISSUE TITLE
Submit Your Bevy's Fourth Birthday Posts Here!

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy-website#1592]
As called out in my [Bevy's Fourth Birthday blog post](https://bevyengine.org/news/bevys-fourth-birthday/), I am highly encouraging everyone to write their own "Bevy Birthday" reflection posts. Just publish your post somewhere (and to social media if you want) and then link to it here. One month from now, we will do a followup "Reflecting on Bevy's Fourth Year" rollup post that aggregates these in one place. This is our chance as a community to celebrate our wins, identify improvement areas, and calibrate our path for the next year!

One callout: Do not criticize or critique specific community members in your posts (other than me and my actions as head of the project ... those are fair game). Critiquing specific community members is not what this platform is for and I will not give it to posts that do this. If you have constructive feedback for people, consider giving it to them personally. If that won't work, talk to our moderation team.

**Comment by Vrixyz** [comment]
My response to the call-out: https://thierryberger.com/blog/bevy-4th-birthday/

**Comment by BD103** [comment]
Here's my post: <https://bd103.github.io/blog/2024-08-18-4-years-of-bevy>

:)

**Comment by alice-i-cecile** [comment]
#1597 is part of this.

**Comment by JMS55** [comment]
https://jms55.github.io/posts/2024-08-30-bevy-fourth-birthday

**Comment by mmatvein** [comment]
[Here's my post on Bevy's reddit.](https://www.reddit.com/r/bevy/comments/1f712hl/bevys_4th_birthday_reflections_in_the_context_of/)

**Comment by mrchantey** [comment]
Thanks for suggesting this! heres my post
https://beetmash.com/blog/bevy-turns-four

**Comment by piedoom** [comment]
My addition is the link at the bottom of the comment! Note that I have it set to draft for now and will remove the 8th (I believe that is the cutoff). I have a [markdown version committed that you can view here right now](https://github.com/piedoom/doomy.org/blob/master/content/2024-09-08-bevys-fourth-birthday/index.md). 

Please do not leave feedback in issue comments, but I would actually be very appreciate of any corrections or fact checking on the technical topics I discuss. If you have a correction or suggestion, please send it to this email alias: github.com.tubeless619@passmail.net). Thanks!

---

Link to use: [https://doomy.org/bevys-fourth-birthday/](https://doomy.org/bevys-fourth-birthday/)

**Comment by ChristopherBiscardi** [comment]
I decided to not re-dns my personal site hours before before taking a week off for rustconf, so here's the post in a gist that I will move to my site in the future 😅 

https://gist.github.com/ChristopherBiscardi/ab3fc92c3ba83e46cb5577bda2d287bc

**Comment by cart** [comment]
This has been posted!

https://bevyengine.org/news/community-reflection-on-bevys-fourth-year/

**Comment by richchurcher** [comment]
Much too late, but FWIW: https://eloquentgeek.games/p/bevy-turns-four/ :laughing:
