### ISSUE TITLE
Automatically sort Book pages by file name

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#161]
Rather than having to specify `weight` in the file header, extract the relevant information (or maybe just sort alphabetically?) from the file name.

**Comment by TrialDragon** [comment]
Is this still desired? As far as I can tell the book pages don't really have a relevant criterion they can each be sorted by outside of explicitly stated weights unless we throw out the concept of the book being ordered (e. g. `getting-started` coming before the other chapters, and the contents within being sorted by importance).

**Comment by alice-i-cecile** [comment]
Yep, this is no longer desired. IIRC we used to label the titles with e.g. 1-chapter-one-title.
