### ISSUE TITLE
TODO link in Contributing Guide

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1611]
Found in https://bevyengine.org/learn/contribute/helping-out/how-you-can-help/#joining-a-working-group

**Comment by alice-i-cecile** [comment]
This is the content it *should* point to: https://bevyengine.org/learn/contribute/project-information/working-groups/

**Comment by TrialDragon** [comment]
Running a grep, theres four total in that page. I'll fix them ASAP.
