### ISSUE TITLE
Bevy Organization link in Foundation page is broken

### ISSUE THREAD

**Issue by mnmaita** [bevyengine/bevy-website#1620]
On this page:

https://bevyengine.org/foundation/

The link pointing to [Bevy Organization](https://github.com/bevyengine/bevy/blob/main/docs/the_bevy_organization.md#maintainer) no longer points to a valid document.

Where is this document hosted now? I can open a PR to fix this.

**Comment by NiklasEi** [comment]
The link has been fixed.
