### ISSUE TITLE
Getting Started Error

### ISSUE THREAD

**Issue by JimLynchCodes** [bevyengine/bevy-website#1621]
I just tried following the [getting started guide](https://bevyengine.org/learn/quick-start/getting-started/), but it doesn't work for me... 😢

step 1) clone bevy:
```
git clone https://github.com/bevyengine/bevy
```

step 2) inside of bevy directory, checkout latest
```
git checkout latest
```

step 3) run example
```
cargo run --example breakout
```

I then see this error message:
```
error: failed to load manifest for workspace member `/Users/jim/bevy/tools/ci`

Caused by:
  failed to parse manifest at `/Users/jim/bevy/tools/ci/Cargo.toml`

Caused by:
  missing field `version`
  in `package`

```

I think the getting started guide is missing some information to get this working... or am I just following it wrong?

**Comment by rparrett** [comment]
It looks like you might be using a version of Rust older than 1.75.0.

This is mentioned outside of the quick start guide, but maybe it might be worth a more explicit mention in the quick start guide. The quick start just mentions "a working Rust setup."

> Bevy relies heavily on improvements in the Rust language and compiler. As a result, the Minimum Supported Rust Version (MSRV) is "the latest stable release" of Rust.
> - https://bevyengine.org/learn/quick-start/getting-started/setup/#installing-rust

**Comment by JimLynchCodes** [comment]
Thanks @rparrett 👍

I would say the error message could be improved also. It seems to be trying to tell me that my project's Cargo.toml is missing a version, _not_ that my cargo version is out of date... 🤔

**Comment by rparrett** [comment]
The error message could potentially be improved by adding [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) to Bevy, but this has been dismissed as impractical. See https://github.com/bevyengine/bevy/issues/288. It would be too onerous to ensure that whatever value we put there is the actual minimum required version at any given time.

**Comment by JimLynchCodes** [comment]
Thanks @rparrett, upgrading my Rust tools solved it. 👍
