### ISSUE TITLE
Write release notes for PR #15458: Runtime required components

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1707]
https://github.com/bevyengine/bevy/pull/15458 needs release notes for the upcoming Bevy release!

Please reply below if you'd like to write these notes. 
While the author(s) of the PR often have the context, knowledge and motivation to draft the release notes for their feature, anyone can contribute release notes!

------

Release notes should:

1. Clearly motivate the change.
2. Be written in a way that is understandable by the average Bevy user: some programming background and a general understanding of games.
3. Show off the coolest features of the PR. Screenshots are awesome, but elegant APIs are also welcome!
4. If this was a perf-centric PR, quantify the performance improvements. Graphs and statistics work well for this.

We can help you revise the release notes: a rough draft alone is incredibly useful :)
Your expertise is invaluable for contextualizing the changes; we'll work with you to bring the technical writing up to par.

To submit your release notes, modify `/home/alice/Documents/bevy-website/release-content/0.15/release-notes/15458_Runtime_required_components.md` and submit a PR.
In that PR, please mention this issue with the `Fixes #ISSUE_NUMBER` keyphrase so it gets closed automatically.

**Comment by Jondolf** [comment]
I'm guessing we can mention this API in the same section as the core `#[require(...)]` API and other things related to required components. Cart [claimed](https://discord.com/channels/691052431525675048/1295069829740499015/1295509188016865330) the Required Components section already, but I can review and write things if needed.

**Comment by alice-i-cecile** [comment]
Yep, I think that this all gets rolled into the big required components section :)

**Comment by cart** [comment]
Yeah I'll claim this one too!

**Comment by cart** [comment]
Closed by #1779
