### ISSUE TITLE
Write release notes for PR #12095: Add features to switch `NativeActivity` and `GameActivity` usage

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1709]
https://github.com/bevyengine/bevy/pull/12095 needs release notes for the upcoming Bevy release!

Please reply below if you'd like to write these notes. 
While the author(s) of the PR often have the context, knowledge and motivation to draft the release notes for their feature, anyone can contribute release notes!

------

Release notes should:

1. Clearly motivate the change.
2. Be written in a way that is understandable by the average Bevy user: some programming background and a general understanding of games.
3. Show off the coolest features of the PR. Screenshots are awesome, but elegant APIs are also welcome!
4. If this was a perf-centric PR, quantify the performance improvements. Graphs and statistics work well for this.

We can help you revise the release notes: a rough draft alone is incredibly useful :)
Your expertise is invaluable for contextualizing the changes; we'll work with you to bring the technical writing up to par.

To submit your release notes, modify `/home/alice/Documents/bevy-website/release-content/0.15/release-notes/12095_Add_features_to_switch_NativeActivity_and_GameActivity_usa.md` and submit a PR.
In that PR, please mention this issue with the `Fixes #ISSUE_NUMBER` keyphrase so it gets closed automatically.

**Comment by Litttlefish** [comment]
Well I can condense some key point here but I have no idea how to connect them:
 - Added two features to allow Bevy choosing between `NativeActivity` and `GameActivity` on Android
 - Changed default `NativeActivity` feature with `GameActivity`, which can be switched back
 - Updated related documentation, including the new workflow and changes to the minimum SDK version, etc
 - Provided Android Gradle projects for both `NativeActivity` and `GameActivity` versions, with the appropriate `libshared_c++.so` fix
 - Mentioned that `cargo-apk` is deprecated due to this change; users should switch to the new workflow, with the original moved to a sub-folder (`android-basic`)
 - Modified Android-related verification jobs (this point is probably not related to the release notes)

**Comment by alice-i-cecile** [comment]
@Litttlefish pretend I've never worked with Android before. What's the difference between `NativeActivity` and `GameActivity`? Why might you choose one over the other?

**Comment by Litttlefish** [comment]
> [@Litttlefish](https://github.com/Litttlefish) pretend I've never worked with Android before. What's the difference between `NativeActivity` and `GameActivity`? Why might you choose one over the other?

It has better input handling, can let rust code(originally C++ though) control more stuff on app level without much jni coding
other stuff can see it [here](https://developer.android.com/games/agdk/game-activity)

**Comment by richchurcher** [comment]
I think the overarching theme here is that few would begin a new project today in the Android world using `NativeActivity` (i.e. `GameActivity` should be considered the new default). The [migration page](https://developer.android.com/games/agdk/game-activity/migrate-native-activity) has additional info. I'm no Android expert, but let's see if I can take a swing at organising some of the above...

> Bevy now uses `GameActivity` as the default `Activity` for Android projects, replacing `NativeActivity`. `NativeActivity` is still available, but has been placed behind a feature flag.
>
> This change updates Bevy to a more modern Android stack, and includes an SDK minimum version bump to [PlayStore's current version requirement](https://developer.android.com/distribute/best-practices/develop/target-sdk). We've also switched to an [NDK](https://developer.android.com/ndk)-based build using [`cargo-ndk`](https://docs.rs/crate/cargo-ndk/3.5.4). Gradle projects for both `GameActivity` and `NativeActivity` are provided.
>
> `GameActivity` brings with it improvements to game interaction (`SurfaceView` rendering, improved touch and input handling), more frequent updates, and access to other parts of the [JetPack]() ecosystem. It is better placed to integrate with Rust code without excessive JNI wrangling. You can read more about `GameActivity` [here](https://developer.android.com/games/agdk/game-activity).

Something along those lines? It's not a terribly familiar area for me, so take with a grain of salt :)

**Comment by Litttlefish** [comment]
also another question: does we need a migration guide for this?

**Comment by richchurcher** [comment]
Possibly? Because if your 0.14 project uses `NativeActivity`, in order to continue to do so you'd need to add a feature flag. Probably the best way to test would be to take a 0.14 project, upgrade the Bevy dependency to 0.15.0-rc.1 and see what changes are required to get it to build.

**Comment by richchurcher** [comment]
See also https://github.com/bevyengine/bevy-website/pull/1754
