### ISSUE TITLE
Write release notes for PR #14848: Improved text batching

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1722]
https://github.com/bevyengine/bevy/pull/14848 needs release notes for the upcoming Bevy release!

Please reply below if you'd like to write these notes. 
While the author(s) of the PR often have the context, knowledge and motivation to draft the release notes for their feature, anyone can contribute release notes!

------

Release notes should:

1. Clearly motivate the change.
2. Be written in a way that is understandable by the average Bevy user: some programming background and a general understanding of games.
3. Show off the coolest features of the PR. Screenshots are awesome, but elegant APIs are also welcome!
4. If this was a perf-centric PR, quantify the performance improvements. Graphs and statistics work well for this.

We can help you revise the release notes: a rough draft alone is incredibly useful :)
Your expertise is invaluable for contextualizing the changes; we'll work with you to bring the technical writing up to par.

To submit your release notes, modify `/home/alice/Documents/bevy-website/release-content/0.15/release-notes/14848_Improved_text_batching.md` and submit a PR.
In that PR, please mention this issue with the `Fixes #ISSUE_NUMBER` keyphrase so it gets closed automatically.

**Comment by alice-i-cecile** [comment]
@ickshonpe do you want to take this one? I would love to hear a small but coherent write-up of your various performance improvements for bevy_ui this cycle.

**Comment by ickshonpe** [comment]
> [@ickshonpe](https://github.com/ickshonpe) do you want to take this one? I would love to hear a small but coherent write-up of your various performance improvements for bevy_ui this cycle.

Sorry had a lot of distractions the last couple of days,  I'm not sure if it's worth a release note, all the text, ghost node and required components changes gobbled up any performance improvements and more.  I can't find a release note issue for the new overflow changes, maybe they need something.

**Comment by alice-i-cecile** [comment]
Sounds good, I'll cut it.
