### ISSUE TITLE
`generate-release-notes` tool missed some PRs that need stubs

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1724]
To add:

- [x] https://github.com/bevyengine/bevy/pull/15320
- [x] https://github.com/bevyengine/bevy/pull/14044
- [x]  https://github.com/bevyengine/bevy/pull/13677
- [x] https://github.com/bevyengine/bevy/pull/13741

EDIT: I can write both of the outstanding PRs that need release notes.

**Comment by alice-i-cecile** [comment]
FYI @TrialDragon

**Comment by TrialDragon** [comment]
May be related to #1518 , Release notes just may not be logging the issue due to having a label passed, unlike in the other steps which has no label.

**Comment by MrGVSV** [comment]
For #1755, I included the following along with the one in #1705:

- [#13321: bevy_reflect: Nested TypeInfo getters](https://github.com/bevyengine/bevy/pull/13321)
- [#13320: bevy_reflect: TypeInfo casting methods](https://github.com/bevyengine/bevy/pull/13320)
- [#15235: bevy_reflect: Add ReflectRef/ReflectMut/ReflectOwned convenience casting methods](https://github.com/bevyengine/bevy/pull/15235)

**Comment by MrGVSV** [comment]
I also would like to add a note for [#14838: bevy_reflect: Add Type type](https://github.com/bevyengine/bevy/pull/14838) as well as just function reflection in general.

**Comment by alice-i-cecile** [comment]
https://github.com/bevyengine/bevy/pull/13669 by @tychedelia was missed too.

**Comment by rparrett** [comment]
https://github.com/bevyengine/bevy/pull/14082 is missing

**Comment by rparrett** [comment]
https://github.com/bevyengine/bevy/pull/14082 still seems missing.

**Comment by rparrett** [comment]
Oops, my bad.
