### ISSUE TITLE
Write Future Work section for 0.15 release notes

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1730]
This should cover at least:

- ghost nodes and UI reactivity
- bevy_cli
- Interaction-yeet
- relations plans
- *maybe* editor prototypes
- more text plans

I'll tackle the first draft of this, and then others can add it to it.

**Comment by Jondolf** [comment]
Also constructs, BSN, and other scene improvements

**Comment by viridia** [comment]
Keyboard focus
