### ISSUE TITLE
Migration Guide for 0.15 mentions UiTextWriter but it is not found when used.

### ISSUE THREAD

**Issue by aidenpc23** [bevyengine/bevy-website#1782]
The Migration Guide mentions UiTextWriter but if you try to use it anywhere it gives this error:
cannot find type `UiTextWriter` in this scope

There is nothing to import.

**Comment by aidenpc23** [comment]
I looked into it and found that it is actually supposed to be TextUiWriter. Migration guide says "UiTextWriter".

**Comment by Olle-Lukowski** [comment]
I personally feel like `UiTextWriter` is a better name... not sure if it's too late to change this, but I will open an issue in the main bevy repo to discuss this.
