### ISSUE TITLE
0.15 Migration: Missing section for 15320 (Retain Rendering World (adopted))

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy-website#1794]
https://github.com/bevyengine/bevy/pull/15320 seems to be missing from https://bevyengine.org/learn/migration-guides/0-14-to-0-15/

**Comment by rparrett** [comment]
Duplicate of #1724

**Comment by rparrett** [comment]
Okay, not a duplicate. That issue is about release notes...

**Comment by alice-i-cecile** [comment]
This is fixed already.
