### ISSUE TITLE
Volumetric fog example shows error "Tex storage 2D multisample is not supported"

### ISSUE THREAD

**Issue by lomirus** [bevyengine/bevy-website#1826]
![Image](https://github.com/user-attachments/assets/5ec3df27-b633-4309-aeec-cbfb1018f331)

Link: https://bevyengine.org/examples/3d-rendering/volumetric-fog/

Browser: Chrome 130.0.6723.117 (Official Build) (arm64)
OS: macOS 14.6.1

**Comment by rparrett** [comment]
Thanks for the report. Tracked over here: https://github.com/bevyengine/bevy/issues/14414
