### ISSUE TITLE
Add a more prominent github link in the header and frontpage

### ISSUE THREAD

**Issue by IceSentry** [bevyengine/bevy-website#188]
Most code-based projects I've used have a link to github. I've seen it fairly often in the header, but it's also sometimes in the frontpage and/or the footer. The only link is currently in the Community tab which wasn't obvious to me.

Examples:

- https://deno.land
- https://reactjs.org
- https://rocket.rs
- https://actix.rs
- https://yew.rs
- https://www.getzola.org
- https://tauri.studio/en/
- https://www.meilisearch.com

After trying to find examples it's not as common as I thought outside of the js ecosystem.

**Comment by TrialDragon** [comment]
I believe this has been solved in #607 ; issue doesn't need to be open any more.
