### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by theRippedPug** [bevyengine/bevy-website#19]
Hey there,
I did not see a license file in the repo so I wanted to ask if it was okay to fork this website to create my own?

**Comment by cart** [comment]
I just added the MIT license to the repo. It is ok for you to fork this website and use the code for your own site, but I will request that you make your own website suitably distinguishable from the Bevy website (in terms of layout, style, colors, and formatting). I spent a lot of time developing a visual identity for Bevy and I'd prefer it if people didn't use it as a "generic template" for their own work.
