### ISSUE TITLE
Properly describe the new MIT-Apache dual license

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#190]
Followup from https://github.com/bevyengine/bevy/pull/2509

"Free and open-source" on the homepage might deserve a call-out.

This could probably go in the book too, but I'm not sure it's important enough / on topic. Those who care can and will check the repo.

**Comment by TrialDragon** [comment]
How should this be re-written? "Licensed under both the MIT and Apache licenses" instead of "Free and open-source forever"?

**Comment by alice-i-cecile** [comment]
"Free and open source forever under your choice of the MIT or Apache 2.0 licenses."
