### ISSUE TITLE
Add dead-link checking to CI

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#197]
This also needs to work for broken short-codes, which are particularly easy to screw up / hard to verify and will break whenever we refactor a referenced item with a rename / module move.

**Comment by alice-i-cecile** [comment]
In order for this to be ergonomic when writing new docs content, we need a way to verify these links against the current `main` branch Bevy API. E.g. I'm attempting to link to `App::add_system`, but on 0.5 (latest) it's still under `AppBuilder`. We need to be able to write and verify docs *before* releases.

https://github.com/bevyengine/bevy/issues/1731 is probably necessary for this to work.

**Comment by alice-i-cecile** [comment]
@mockersf noted that one of the largest difficulties in fully solving this will be verifying that method / field calls are valid. Missing types etc return a 404, but that's not the case if the anchor (i.e. `#method.get`) is wrong. We may need to tweak an existing dead link checking script to work specifically with the Rust doc sites information in a smarter way.

That said, even basic 404 checking would help improve quality significantly.

**Comment by cart** [comment]
> In order for this to be ergonomic when writing new docs content, we need a way to verify these links against the current main branch Bevy API. E.g. I'm attempting to link to App::add_system, but on 0.5 (latest) it's still under AppBuilder. We need to be able to write and verify docs before releases.

Yup good points. I think we can find a way to make the version "globally configurable" for short codes. Either by just manually modifying the shortcode impl or by using some sort of "global version config".

> @mockersf noted that one of the largest difficulties in fully solving this will be verifying that method / field calls are valid. Missing types etc return a 404, but that's not the case if the anchor (i.e. #method.get) is wrong. We may need to tweak an existing dead link checking script to work specifically with the Rust doc sites information in a smarter way.

Arg I wasn't aware of that. I agree that we should ultimately add some custom logic here. I also agree that basic 404 checking is a good start.

I also want to eventually adopt our own "rust based dead link validator task" if possible. I don't like that users cant easily do dead link checks on their machines. In the same way that they can do clippy and fmt validations.

**Comment by alice-i-cecile** [comment]
Duplicate of #177.
