### ISSUE TITLE
Add shortcode modifier to allow for ommision of type on methods

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#199]
When discussing methods in more casual forms of docs / news, the struct / trait that a method belongs to will often be obvious or omitted.

By adding a `no_type` mechanism, we can discuss things like `.before` with an automatic link to the docs but without including the `IntoExclusiveSystemDescriptor` trait in the flow of the text.

**Comment by cart** [comment]
I dig this!
