### ISSUE TITLE
Add a (curated?) section to the bevy website to include games created by the community

### ISSUE THREAD

**Issue by GabLotus** [bevyengine/bevy-website#2]
A particular emphasis on open source games would be particularly useful to newcomers who want further examples of how to use the engine.

![image](https://user-images.githubusercontent.com/25371684/89936682-dadbc700-dbc8-11ea-8449-0f8836e1430c.png)

**Comment by cart** [comment]
I love it. Lets start brainstorming what such a page would look like.

**Comment by morr0ne** [comment]
Would it peraphs makes sense to add [awesome-bevy](https://github.com/bevyengine/awesome-bevy) to the site?

**Comment by jamadazi** [comment]
We already have Awesome-Bevy as the official de-facto "hub" for featuring community work.

I'd rather feature that on the website, rather than create and maintain a new page, which would really just contain duplicate information.

**Comment by cart** [comment]
Ultimately I would like to replace Awesome Bevy on github with a more searchable / graphical implementation in `bevy-website` (although it might still feed off of a schematized awesome-bevy repo). But yeah for now awesome-bevy fills that niche.

**Comment by morr0ne** [comment]
Awesome-bevy is enough right now but we should probably think about the future. Someday bevy may (hopefully) become much bigger and awesome-bevy could become a mess (just look at [awesome-nodejs](https://github.com/sindresorhus/awesome-nodejs)). A more indexable and easier to navigate version on the website would be nice

**Comment by alice-i-cecile** [comment]
This is now done as part of "Bevy Assets".
