### ISSUE TITLE
Support use of generics in short codes

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#201]
For example, I want to convert [`SystemState::<Commands>::apply()`](https://docs.rs/bevy/latest/bevy/ecs/system/struct.SystemState#method.apply) to short-codes, but have no way to do so without losing important clarity.

**Comment by cart** [comment]
Yeah this is interesting. I think we could probably make this an array of strings (one for each generic parameter) passed into the shortcode.
