### ISSUE TITLE
Update the style to make the book sidebar wider

### ISSUE THREAD

**Issue by IceSentry** [bevyengine/bevy-website#213]
Right now, the book section titles are much longer than the width of the sidebar which makes them harder than necessary to read. 

I see a few solutions:

1. Make the sidebar wider, but keep everything else as-is. 350px width seems to be a nice width from my quick testing.
![image](https://user-images.githubusercontent.com/8348954/137764398-642803ab-40a0-4632-9f4d-94d1deb7c6ca.png)

2. Make the sidebar left aligned like mdbook so it will have a lot more place to show the titles. This would probably also need to make the main body text slightly less wide.
![image](https://user-images.githubusercontent.com/8348954/137764908-a4d8ba67-0f05-43bd-a253-934d09e12c6a.png)

My edits were done directly in the devtools just to give a quick idea.

**Comment by TrialDragon** [comment]
Is this still relevant or desired for the modern site?

**Comment by IceSentry** [comment]
I think the main issue was caused by using numbers. It doesn't have the same issue now.

**Comment by TrialDragon** [comment]
So this issue can be closed then?

**Comment by IceSentry** [comment]
Yeah, I guess so
