### ISSUE TITLE
Add a warning similar to the one on github in the landing page

### ISSUE THREAD

**Issue by IceSentry** [bevyengine/bevy-website#218]
The main github repo has a warning at the top of the README explaining that bevy is still very much a work in progress. Currently the website isn't nearly as obvious about this. It might be better for beginners if there was a similar warning right on the landing page.

**Comment by BD103** [comment]
There is a stability warning in the [introduction page](https://bevyengine.org/learn/quick-start/introduction/). Do you want something more than this?

**Comment by alice-i-cecile** [comment]
Agreed, I think we're fine now.
