### ISSUE TITLE
Shortcodes seem to insert strange line breaks when used as the first word in a paragraph

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#219]
As seen in https://github.com/bevyengine/bevy-website/pull/182#issuecomment-936311931

**Comment by alice-i-cecile** [comment]
This either needs to be fixed or worked around for the new book launch.

**Comment by cart** [comment]
Yup I hit this too awhile back. It feels like a zola bug to me. The "fix" is to add text in front of the short code, but obviously that isn't a real solution to the problem.
