### ISSUE TITLE
Deployed previews for website PRs

### ISSUE THREAD

**Issue by NiklasEi** [bevyengine/bevy-website#223]
It would be very nice to have deployed previews of every PR for the website. I think this would encourage more reviews and feedback for open changes (e.g. the new book).

I would like to combine this with having a deployed "development" version of the website that shows the website for Bevy's `main` branch. That would allow us to update the website book/tutorials alongside Bevy for future updates and would offer already deployed resources for people running on Bevy's `main` branch. It makes sense that the main website is for the latest release, but we do have a lot of users running on `main`, so I think it would be awesome to have a link like `https::/main.bevyengine.org` with the latest book, tutorials, and error codes for Bevy's `main` branch (another option would be to have the same domain, but a path for main; e.g. `/learn/main/book`).

Personally, I am a big fan of Netlify, but I am not sure if this would be a good fit here. We would probably hit the 300 build minutes per month that come with the free plan due to our daily builds (+ PR previews). They do offer an [open source plan](https://www.netlify.com/legal/open-source-policy/), but that would require us to link back to their service. Maybe that is something we would be willing to do for previews?
There are probably many other services that would offer something similar. Maybe there is a better fitting option out there, any ideas?

**Comment by alice-i-cecile** [comment]
I would like this: it would make reviewing book PRs much easier. @mockersf, perhaps this would be a compelling use of the hosting offer you were looking at?

**Comment by NiklasEi** [comment]
Closing for #313
