### ISSUE TITLE
Add a link to the Bevy Assets page explaining how to contribute your own examples

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#238]
https://github.com/bevyengine/bevy-assets is the way to do this, but it's not at all obvious to new contributors.

**Comment by TrialDragon** [comment]
Would this be a page in the contributing section of the book, or just a link on a preexisting page? If it should be a page in the contributing section of the book, then what in all should it's contents entail?

**Comment by alice-i-cecile** [comment]
![image](https://github.com/bevyengine/bevy-website/assets/3579909/19b91d05-176c-402e-b144-9c09ac0ce519)

This appears to be already fixed :)
