### ISSUE TITLE
Add chapter on plugin development

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#298]
Begin by migrating content from https://github.com/bevyengine/bevy/blob/main/docs/plugins_guidelines.md

**Comment by TrialDragon** [comment]
Past migrating the preexisting third party plugin guidelines, what should this chapter cover in it's contents?

**Comment by alice-i-cecile** [comment]
Hmm. I think it should link to the Rust API guidelines and information about semantic versioning in Rust. CI advice is also useful.

Generic plugin types might be a good fit here too: that's a good trick that rarely comes up when making games, but is common in plugins.

**Comment by TrialDragon** [comment]
Okay, what regarding CI should I look into to add? The content gotten from the guidelines already introduces an example of CI using GitHub Actions. 

Also, what is the bare basics of this Generic Plugin Types in relation to third party plugins? I'm unaware of this specific context / circumstance and haven't found much info regarding this looking it up.

**Comment by TrialDragon** [comment]
Another question; should this chapter be guidelines / providing direct info oriented like the third party plugin guidelines it originates from, or should it be more like a tutorial going through the process of creating a plugin in a sense providing info as it goes?

**Comment by alice-i-cecile** [comment]
> Okay, what regarding CI should I look into to add? The content gotten from the guidelines already introduces an example of CI using GitHub Actions.

For an initial PR, I'd be fine with just keeping it unmodified. Eventually, I'd like to teach a bit more about how to do CI effectively in Rust / Bevy, but that probably deserves its own dedicated chapter.

> Another question; should this chapter be guidelines / providing direct info oriented like the third party plugin guidelines it originates from, or should it be more like a tutorial going through the process of creating a plugin in a sense providing info as it goes?

For now, I think we should aim for a pretty direct port: my main goal is to migrate all of the scattered documentation onto the main website, where it will actually be discoverable.
