### ISSUE TITLE
Compress Feature page layout

### ISSUE THREAD

**Issue by IceSentry** [bevyengine/bevy-website#308]
The current feature page shows a lot of good stuff, but it requires a whole lot of scrolling. We could pretty easily put the images showcasing a feature to the left or right of the text to be able to fit a lot more stuff on the page.

https://amethyst.rs is a decent example of what I'm suggesting.

![image](https://user-images.githubusercontent.com/8348954/160924516-f1a4376c-2b52-4c01-bd19-073cbdda8d46.png)

https://godotengine.org does it a bit differently, but it has multiple feature on each line so it's still more compressed than us.

![image](https://user-images.githubusercontent.com/8348954/160924587-46144bcd-80fd-4e2c-9468-0fa54f0fc53b.png)

**Comment by ramon-bernardo** [comment]
I like godot's feature menu, it's simple and flashy

**Comment by IceSentry** [comment]
Just to add a bit more context. The issue was actually because I used a default font size of 18 instead of 16. When using 16 the website was already working correctly with images next to the text.

**Comment by TimJentzsch** [comment]
I think this should be closed as completed by #315
