### ISSUE TITLE
Improve examples section layout/styling

### ISSUE THREAD

**Issue by doup** [bevyengine/bevy-website#336]
Examples section is now visible on the `Learn` section, #335. But it's a little bit raw and it could use some styling improvements. Some suggestions by Cart ([discord](https://discord.com/channels/691052431525675048/695741366520512563/964332377390338078)):

```
I just started a merge for https://github.com/bevyengine/bevy-website/pull/335. If anyone is interested in
sprucing up the example layout a little bit, I think thats worth prioritizing. (ex: rounded corners for the
example canvas to match the code blocks, a nicer back button, ideally some sort of canvas resizing to
make it fit within the bounds of the content areas / work on mobile)
```

**Comment by alice-i-cecile** [comment]
#350 is a first step towards this.

**Comment by cart** [comment]
I'm comfortable closing this now. @doup has done a great job here.
