### ISSUE TITLE
Mark code that shouldn't compile or fails in runtime

### ISSUE THREAD

**Issue by adsick** [bevyengine/bevy-website#343]
The official Rust book has fancy Ferris showing whether a given snippet compiles or not [like so](https://doc.rust-lang.org/book/ch00-00-introduction.html#how-to-use-this-book). Rust documentation system has it too (no Ferris tho)

So I suggest following that and explicitly show that a piece of code won't compile or will give a runtime error.
e.g. in recent 0.7 blog post we have this https://bevyengine.org/news/bevy-0-7/#world-system-param chapter and it would be a bit better if the code snippet after "... &World will conflict with any mutable Query:" was made into reddish borders or had a corresponding label.

**Comment by alice-i-cecile** [comment]
Now that #348 is in, this should be a simple matter of adding this to the places where it should be :) I think we just have the news post for now.

Do you think we should add this to our "compiler error" output too?

**Comment by adsick** [comment]
That was quick)

> Do you think we should add this to our "compiler error" output too?

not sure what do you mean

**Comment by alice-i-cecile** [comment]
I was definitely imprecise there. I meant general error messages like seen at https://bevyengine.org/learn/book/troubleshooting/

**Comment by adsick** [comment]
Yeah, that may be a nice addition.

**Comment by TimJentzsch** [comment]
The [given example](https://bevyengine.org/news/bevy-0-7/#world-system-param) is already marked in red, does this need to be added anywhere else or can this be closed?
