### ISSUE TITLE
Stress Test >  BevyMark example doesn't load (404 error)

### ISSUE THREAD

**Issue by doup** [bevyengine/bevy-website#351]
BevyMark errors with a 404:
- https://bevyengine.org/examples/stress-tests/bevymark/

**Comment by DJMcNab** [comment]
The correct link is https://bevyengine.org/examples/stress_tests/bevymark/.

Not sure how it ended up as the wrong link

**Comment by mockersf** [comment]
this is due to the "slugify" there: 
https://github.com/bevyengine/bevy-website/blob/55027e2820c69ccb618422f0313a9e52e6b0fec0/templates/examples.html#L26

**Comment by doup** [comment]
I think `category_path=`echo $2 | tr '_' '-'`` on the script once #350 merges should do the trick.
What do you think?
