### ISSUE TITLE
Suggest that users use `cargo add` command to add Bevy

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#356]
[Merged PR](https://github.com/rust-lang/cargo/pull/10472) for the feature.

This spares users from having to reason about the `Cargo.toml` directly, and makes sure they're always using the latest release.

We should probably wait a bit to make sure that this lands.

**Comment by epage** [comment]
Yes, it'll be a couple of Rust release before this hits stable.  As precedence for changing the book, we hope to update crates.io as well to provide `cargo add` snippets.

Just wanted to call out that more than
```console
$ cargo add bevy
```
(like on [quick start](https://bevyengine.org/learn/book/getting-started/))

You can also do
```console
$ cargo add bevy -F dynamic
```
(like on [setup](https://bevyengine.org/learn/book/getting-started/setup/))

**Comment by IceSentry** [comment]
This isn't blocked anymore, but there was some pushback on discord based on some people not liking the higher risk of typo squatting related to using cargo add. I don't necessarily agree, but it's worth considering before merging anything.

**Comment by alice-i-cecile** [comment]
I agree; I don't think that's a particularly important concern here. Users will be running this on their home machine, and I trust the cargo team's judgement on the relative security costs.

**Comment by epage** [comment]
I have not heard of any concerns before for typo squatting (nor can I think of it being any different than editing `Cargo.toml`).

Could you point people with those concerns to our typo squatting issues so we can keep their concerns in mind when prioritizing them?
- https://github.com/rust-lang/cargo/issues/10655
- https://github.com/rust-lang/cargo/issues/10656

We can then also keep it in mind with my request to put cargo-add snippets on crates.io: https://github.com/rust-lang/crates.io/discussions/4980
