### ISSUE TITLE
Incomplete website display on Android phone

### ISSUE THREAD

**Issue by C-BJ** [bevyengine/bevy-website#382]
The browsers is using Chrome kernel
A small part on the left is beyond the screen
Has there ever been a PR or issue related to this issue before? I seem to remember, but I can't find it.

**Comment by awulkan** [comment]
What's your phone resolution and zoom level? I can't see anything wrong with the website on my Pixel 6.

**Comment by BD103** [comment]
I'm not able to reproduce this, even when messing with the screen size and responsiveness in Firefox devtools. If this is still an issue, feel free to respond and we can figure something out!
