### ISSUE TITLE
Some web examples fail to render

### ISSUE THREAD

**Issue by aaronsantiago** [bevyengine/bevy-website#384]
Currently for some examples like: https://bevyengine.org/examples/2d/sprite-sheet/ and https://bevyengine.org/examples/stress-tests/bevymark/ the output is only grey.

Output:
![unknown (2)](https://user-images.githubusercontent.com/47049060/174095681-69250dcf-5cf9-45c6-9901-6a1a3c705b68.png)

Console:
![unknown (1)](https://user-images.githubusercontent.com/47049060/174095624-8146c703-0e70-4f0f-8dbb-e8d5d7ec7df9.png)

I've tested this with the same result in Edge, Chrome, and Firefox on Windows, and Chrome and Firefox on OSX.

**Comment by mockersf** [comment]
related to #355 
@doup or @ickk any ideas why the custom fetch is failing now?

**Comment by mockersf** [comment]
https://crates.io/crates/wasm-bindgen was updated 2 days ago and probably changed the js generated, and https://github.com/bevyengine/bevy-website/blob/75acb730406ef9c5928d37daf8bb32e4dbeb8b13/generate-wasm-examples/generate_wasm_examples.sh#L44-L48 probably fail to update it correctly
