### ISSUE TITLE
Add instructions on how to set up Assets and Examples page locally

### ISSUE THREAD

**Issue by TimJentzsch** [bevyengine/bevy-website#423]
When testing the website locally, I get a 404 error when trying to access the Assets and Examples pages.

I assume I have to run the `generate-assets/generate_assets.sh` script to do that.

This information should be accessible via the README file to make it easier for new contributors to set everything up.

**Comment by oCaioOliveira** [comment]
Hello @TimJentzsch, @ErickMVdO and me oppened a [PR](https://github.com/bevyengine/bevy-website/pull/496) for this issue with a better description how to acces Assets.
