### ISSUE TITLE
Broken Assets Page

### ISSUE THREAD

**Issue by Dash-L** [bevyengine/bevy-website#444]
I couldn't seem to find any other issues mentioning this, so maybe it's just me (or I missed something obvious), but if I go to the [assets](https://bevyengine.org/assets/) page, it just has the headings and nothing else:
![image](https://user-images.githubusercontent.com/48158656/185248928-7b217efe-0a1d-4047-bfee-9149af225afd.png)

I tested this on firefox (regular and in private browsing) and chromium (which has no extensions), so if it is on my side, I'm not sure what it would be.

**Comment by rparrett** [comment]
Reverting [these changes](https://github.com/bevyengine/bevy-website/commit/1651ab3e73b859bab4476021410facc21b871ac4#diff-00899f4d780d4e1734dd4ebb65007497fd14256074bb928a8ed1ac4fb91c031d) fixes the issue

**Comment by Dash-L** [comment]
great, thanks!
