### ISSUE TITLE
Asset card image containers should have a constant aspect ratio

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy-website#448]
Currently, the cards change in width with the screen size.

This means that there is no image aspect ratio that will "look good" on all screen sizes. Even if all images were authored with a consistent aspect ratio, they would be letterboxed on some screens. The aspect ratio also ends up pretty extreme on large mobile displays in portrait mode.

It would be great to rework the cards so that the aspect ratio of the image container is consistent across screen sizes.

See also: [discord conversation](https://discord.com/channels/691052431525675048/695741366520512563/1009903697494556755)

**Comment by oCaioOliveira** [comment]
Hello @rparrett, I've been new here and I'm trying to contribute. This issue still open? Running the clone of your repository looks the problem are solved, can you confirm this?

**Comment by rparrett** [comment]
Cool!

Here's a screen recording that hopefully clears up what I attempted to describe in the issue text.

https://user-images.githubusercontent.com/200550/203440984-f2741046-3118-4311-b6b1-72dbe8f3b9b1.mp4

Right now, if someone submits their project to Bevy Assets, they always have to compromise when they choose the aspect ratio for their cover image because it is likely to be different on various screen sizes.

**Comment by rparrett** [comment]
Maybe the least clear part of the issue text is saying that the "image" should have a constant aspect ratio. They're not getting squished or anything, but the container's aspect ratio is changing so the images are displayed with inconsistent letterboxing.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/200550/203441918-49b987b7-cb2c-45fe-a84b-3d361a1629ac.png">

<img width="374" alt="image" src="https://user-images.githubusercontent.com/200550/203442000-a25fcf60-810f-4268-9e7e-d4b1831c524a.png">

**Comment by oCaioOliveira** [comment]
Ok, thanks for the extra description @rparrett, I'll work on it.

**Comment by oCaioOliveira** [comment]
I worked on it with @ErickMVdO, and this is the result @rparrett. Is it what you needed?
The PR it's open.
[Video demonstration](https://youtu.be/8TEz34Y7ylY).
