### ISSUE TITLE
Better documentation of installing alternative linker in setup guide

### ISSUE THREAD

**Issue by chrisburnor** [bevyengine/bevy-website#45]
I like that the Bevy Guide provides directions for a better linker in the [setup guide](https://bevyengine.org/learn/book/getting-started/setup/).

However as the documentation stands, $YOUR_WORKSPACE is unclear across platforms and there is no way to verify if the config is working or not.

**Comment by shirshak55** [comment]
For verifying: Hi you can use --verbose when running cargo run which can tell if you are using lld or not. And lld are for linux and windows and for osx there is something called zld which can be used as linker. Its mentioned on "Enable Fast Compiles" at the time of writing. 

$YOUR_WORKSPACE is just a folder where Cargo.toml resides. 

By the way you can use lld as global config by modifying ```~/.cargo/config```. However I find global config using lld problematic for some project like substrate.
