### ISSUE TITLE
Docs tell contributors to run clippy with incomplete set of lints.

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy-website#458]
https://github.com/bevyengine/bevy/pull/4665 added some new clippy lints a while back, but

https://github.com/bevyengine/bevy-website/blob/master/content/learn/book/contributing/code/_index.md?plain=1#L20

still tells you to run the old set of lints.

This seems to be what CI is running now:

`cargo clippy --workspace --all-targets --all-features -- -A clippy::type_complexity -W clippy::doc_markdown -W clippy::redundant_else -W clippy::match_same_arms -W clippy::semicolon_if_nothing_returned -W clippy::explicit_iter_loop -W clippy::map_flatten -D warnings`

Which is a bit of a mouthful.

**Comment by mockersf** [comment]
keeping that information synced between code used by CI, https://github.com/bevyengine/bevy/blob/main/CONTRIBUTING.md and https://github.com/bevyengine/bevy-website/blob/master/content/learn/book/contributing/code/_index.md seems a bad idea, could we remove at least one of them?

**Comment by mockersf** [comment]
> Can we just add #[allow(clippy::type_complexity)] etc. to every crate?

To be honest I think we should stop allowing it on clippy level and just allow it on lines where it's needed instead of everywhere.

**Comment by TrialDragon** [comment]
To see if I understand correctly: The desired solution is to remove the redefinition of the manual command so as to avoid having to maintain changes to it as it changes. Instead just leave the regular CI command in the book?

**Comment by mockersf** [comment]
we are moving more and more to clippy configuration, and lint management on crate level, so I'm not sure this part is relevant anymore

**Comment by BD103** [comment]
The contributing section of the website has been removed to prevent duplicated and outdated information. This issue is no longer applicable.
