### ISSUE TITLE
Discussion: use mdBook for documentation

### ISSUE THREAD

**Issue by nic96** [bevyengine/bevy-website#47]
I was wondering why [mdBook](https://rust-lang.github.io/mdBook/) wasn't being used for documentation and found @cart commented about this on Discord. I'll quote what he said for anyone else wondering and maybe we can discuss the idea.

Quote of @cart's message on Discord:
> I've been playing around with that idea for awhile. It's clearly the more feature complete solution, but I don't want to lose the "integrated feel" of the current implementation. I also think using the same codebase for all website contributions keeps things nice and simple.
>
> It's worth opening an issue to capture this

For myself the "integrated feel" doesn't matter with the documentation. Many awesome open source projects have a separate docs website which I don't mind at all. Bevy could have a `docs.bevyengine.org` where the documentation would reside at or maybe `book.bevyengine.org` which seems to be the style for rust projects.

**Comment by shirshak55** [comment]
In my point of view I agree with Carl. Its much better than mdbook.  Plus there are control that's hard in mdbook in my opinion.

**Comment by alice-i-cecile** [comment]
Per #143 it looks like we're going to be hacking Zola to get the missing features we need. I'm going to close this for now; we can reopen it if needed.
