### ISSUE TITLE
Fix Bevy version detection for assets with Cargo workspaces

### ISSUE THREAD

**Issue by TimJentzsch** [bevyengine/bevy-website#475]
Some of the assets on the website display with as using an old version of Bevy, even though they use the current one:
![bevy_tiled on the assets page, showing as using Bevy 0.5, but it uses Bevy 0.8](https://user-images.githubusercontent.com/13908946/200692478-765cc500-8fae-4132-93e5-d76f894906ec.png)

My guess is that this is caused by the project using Cargo workspaces:
<https://github.com/MrGVSV/bevy_tileset/blob/9154f887fccd1e4374caaaae44dedc2d69a5184c/Cargo.toml#L14-L15>

The system should either correctly resolve the workspaces and try to find the Bevy version in the workspace members, or not display a version at all if it cannot be found.
Displaying an older version like this makes it seem like the library is unmaintained.

**Comment by rparrett** [comment]
That project was previously not using a workspace, so the issue would seem to be old data hanging around from a time when we could determine the version not being overwritten by new data.

Workspaces are super common though so it would be nice if we could get that data.

**Comment by mockersf** [comment]
the script is looking for the `Cargo.toml` file, and then in it for the first dependency whose name starts with `bevy`

for this crate it's `bevy_tileset_tiles = { path = "./bevy_tileset_tiles", version = "0.5" }`, so version is 0.5

**Comment by TimJentzsch** [comment]
I think we should change it to look for an exact match.
It might also be feasible to look for the `workspace` property and then to try and fetch the `Cargo.toml` of the workspace members to see if they depend on Bevy directly.

It also looks like the metadata cannot be unset, once it's set:
<https://github.com/bevyengine/bevy-website/blob/master/generate-assets/src/lib.rs#L44-L51>

This seems wrong to me and might also result in out-of-date entries.

**Comment by mockersf** [comment]
It's not a workspace issue, the crate `bevy_tileset` doesn't depend directly at all from Bevy: https://crates.io/crates/bevy_tileset/0.5.0/dependencies. So the script would need to load each dependency, then check if one of those dependency depends on Bevy. That's dependency resolution, and out of the script scope for now unless it starts to depend on `cargo` somehow.

For the exact match, some people prefer to depend on sub crates like `bevy_ecs` rather than `bevy` directly 🤷 

It's not possible to get out-of-date entries because everything is computed from scratch each time the script is ran. The function you're linking will not override the version if, during the same run, we find version information from several sources (crates.io, GitHub, ...)

**Comment by TimJentzsch** [comment]
> It's not a workspace issue, the crate bevy_tileset doesn't depend directly at all on Bevy: https://crates.io/crates/bevy_tileset/0.5.0/dependencies.

Yes, but it depends on `bevy_tileset_core`, which is a workspace member, and that depends on `bevy`:
<https://github.com/MrGVSV/bevy_tileset/blob/9154f887fccd1e4374caaaae44dedc2d69a5184c/bevy_tileset_core/Cargo.toml#L16>

So we could check if a bevy dependency is in Cargo.toml, otherwise we check if it is a workspace and then check the members of that workspace for a direct dependency.
That would probably not cover all cases, but I think it's common enough to warrant some extra logic in the script.

> For the exact match, some people prefer to depend on sub crates like `bevy_ecs` rather than `bevy` directly :shrug: We could improve maybe by looking first for an exact match, then a starts with if none is found.

Hmm, that's a good point. Either that, or we define a list of common "official" dependencies. Personally, I think it's better if we miss the Bevy version than getting a wrong one (which might suggest that the asset is unmaintained when it isn't).

> It's not possible to get out-of-date entries because everything is computed from scratch each time the script is ran. The function you're linking will not override the version if, during the same run, we find version information from several sources (crates.io, GitHub, ...)

That's good to know. Maybe we should allow the asset authors to provide multiple links in the future (e.g. repo link, crates.io link, etc.) so that we have more options to get the data from.

**Comment by mockersf** [comment]
> So we could check if a bevy dependency is in Cargo.toml, otherwise we check if it is a workspace and then check the members of that workspace for a direct dependency.

That would be hard coding a special case that is wrong. There are no guarantee that a workspace member is a dependency of the root crate of a repo. To do properly, it would mean we should start looking at dependencies of the root crate, then check if they are in the workspace, then open their `Cargo.toml` files... dependencies resolution.

For this case, I think we should not display a Bevy version if there isn't one as a direct dependency of the crate linked. So solving the "fuzzy" search for an official `bevy` crate.

We could just add a few crate names that would be the most common, `bevy`, `bevy_ecs`, `bevy_app`, `bevy_render`, ... or find a way to reuse this list https://github.com/bevyengine/bevy/blob/1914a3f288a812667f735ee9e7806cf1560dacc0/tools/publish.sh#L3-L40

**Comment by mockersf** [comment]
or the crate could add `bevy` as a direct dependency
