### ISSUE TITLE
ECS example on Getting Started doesn't work properly

### ISSUE THREAD

**Issue by jmrepetti** [bevyengine/bevy-website#48]
I think the example described in https://bevyengine.org/learn/book/getting-started/ecs/ should be updated, now you'll need
to provide a plugin with a SchedulerRunnerPlugin mode, otherwise the app.initialize() is not called and I only see one line in the output instead of the list of people.

Here is a possible modification:

```
// update use
use bevy::{app::ScheduleRunnerPlugin, prelude::*};

fn main() {
    App::build()
        .add_startup_system(add_people.system())
>>>>        .add_plugin(ScheduleRunnerPlugin::run_once())
        .add_system(hello_world.system())
        .add_system(greet_people.system())
        .run();
}
```

**Comment by alice-i-cecile** [comment]
This is now outdated <3

**Comment by Fritzoid** [comment]
The ECS getting started chapter is still not 'working'. It's a bit of a turn off when the first example code you run into when trying to learn something new, can't compile. The hello_world system in the first example doesn't exist.

**Comment by mockersf** [comment]
@Fritzoid are you speaking about https://bevyengine.org/learn/book/getting-started/ecs/#your-first-system? The `hello_world` system is the function in the first code block
