### ISSUE TITLE
Check for dead links in CI

### ISSUE THREAD

**Issue by doup** [bevyengine/bevy-website#511]
As part of #504 I've found a dead link by chance, `becy_core::Time` is now in `bevy_time::Time` so the documentation link was broken.

Add something like this to the CI "linting stage": https://github.com/marketplace/actions/markdown-link-check

**Comment by mockersf** [comment]
we use to have such a check in CI in Bevy main repo, but ended up removing it because it had too many false positive

**Comment by doup** [comment]
OK… I see, then I suppose this can be closed. If anyone finds a broken link they can open an issue/PR. 🤷‍♂️
