### ISSUE TITLE
Mold will no longer support Windows

### ISSUE THREAD

**Issue by FlooferLand** [bevyengine/bevy-website#535]
It was announced last month that [Windows support for Mold won't be added due to development costs](https://github.com/rui314/mold/issues/190#issuecomment-1402841196), and that Windows compatibility has been [moved to Sold](https://github.com/bluewhalesystems/sold/issues/1) (the commercial/paid variant of Mold)

Very small improvement, but I figured I'd mention it.
I'm not sure if there is a linker faster than LLD on Windows that could be recommended _(I can't find anything)_ so I didn't open a pull request in case anyone has an alternative. I also have no clue how Zola works.

Hopefully my tiny doc change helps a bit!

**Comment by TrialDragon** [comment]
This appears to be have been resolved in #781, commit https://github.com/bevyengine/bevy-website/commit/89e8601045a188badc032a2b1ff859b05617810a .
