### ISSUE TITLE
Add an "OS Dependencies" section to The Book's Setup page

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy-website#6]
Users (especially on linux) often don't have the required dependencies to build bevy. It would significantly reduce friction to provide the list for them.

This should extend the existing Setup page with something like:

```markdown
## Install OS Dependencies
* [Linux](https://github.com/bevyengine/bevy/docs/linux_dependencies.md)
* Windows: You should be good to go!
* MacOS: No dependencies here!
```

Then the bevy repo would contain `linux_dependencies.md` with one section for each linux variant.

**Comment by MatteoGgl** [comment]
I'm willing to take care of this. Is there any document or reference for the required deps?

I already know about these two:
`libx11-dev`
`libasound2-dev`

**Comment by cart** [comment]
those are the only ones I'm aware of. but its possible im missing something. we can always add more later if new ones come up.
