### ISSUE TITLE
All examples aren't loading (404)

### ISSUE THREAD

**Issue by Andrewp2** [bevyengine/bevy-website#619]
I tried loading a couple of examples from the website (https://bevyengine.org/examples/) today, and they all return with an error (like):

`GET https://bevyengine.org/examples/3d/pbr/pbr.js net::ERR_ABORTED 404`

**Comment by mockersf** [comment]
Should work now after a rebuild 👍 

Thanks for reporting!

**Comment by Andrewp2** [comment]
Can confirm works for me!
