### ISSUE TITLE
Server Not Found

### ISSUE THREAD

**Issue by comblock** [bevyengine/bevy-website#632]
I'm getting a Server Not Found error when trying to open the website. 

I don't get the error on mobile (same network, possibly different wifi access point) but on linux and windows I do get the error.

**Comment by cart** [comment]
Is this still happening?

**Comment by comblock** [comment]
> Is this still happening?

It is

**Comment by cart** [comment]
Is there any other error information? This could be a problem with your network setup, github page's CDN, or really anything.

**Comment by comblock** [comment]
> Is there any other error information? This could be a problem with your network setup, github page's CDN, or really anything.

Where could I find additional error info if there is any?

**Comment by comblock** [comment]
I don't know why but it works now

**Comment by comblock** [comment]
It stopped working

**Comment by comblock** [comment]
It's still not working for me and it's really annoying

**Comment by mockersf** [comment]
Do other sites on GitHub pages like https://jekyllrb.com work for you?
If you use another DNS like [1.1.1.1](https://www.cloudflare.com/en-gb/learning/dns/what-is-1.1.1.1/) does it fix it?
if you run `ping bevyengine.org`, `dig bevyengine.org`, `nslookup bevyengine.org` or `traceroute bevyengine.org` (this one will have personal informations in its output, don't paste it), are there error?

**Comment by comblock** [comment]
> Do other sites on GitHub pages like https://jekyllrb.com work for you?
Yes, as far as I know, bevyengine.org is the only one that doesn't work.

output from the commands:
```sh
comblock@DESKTOP-BC04AP1:~> ping bevyengine.org
ping: bevyengine.org: Name or service not known
comblock@DESKTOP-BC04AP1:~> dig bevyengine.org

; <<>> DiG 9.18.16 <<>> bevyengine.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 64305
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;bevyengine.org.                        IN      A

;; Query time: 95 msec
;; SERVER: 192.168.1.1#53(192.168.1.1) (UDP)
;; WHEN: Mon Jul 10 17:08:24 CEST 2023
;; MSG SIZE  rcvd: 43

comblock@DESKTOP-BC04AP1:~> nslookup bevyengine.org
Server:         192.168.1.1
Address:        192.168.1.1#53

** server can't find bevyengine.org: SERVFAIL
```

I tried using 1.1.1.1 but that didn't change anything.
(I used method 1 from https://en.opensuse.org/SDB:Configure_DNS to set it up)

**Comment by mockersf** [comment]
You have a DNS server on your local network at `192.168.1.1` that is blocking bevyengine.org resolution

**Comment by comblock** [comment]
After restarting my computer it actually works now with 1.1.1.1
Any idea why there would be a local DNS server that's blocking bevyengine.org?

**Comment by mockersf** [comment]
Is your network administrator a die hard fan of unity? Joke aside, without knowing a lot more about your local network setup, it's going to be hard to help you there...
