### ISSUE TITLE
Remove link to Reddit (/r/bevy)

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#651]
The ongoing mismanagement of Reddit is concerning and frustrating: we followed the protest, but are now being forced to reopen.

![image](https://github.com/bevyengine/bevy-website/assets/3579909/984bfe14-7fac-4abb-9366-9a8f97c77034)

This is likely to continue to degrade: we should pull our links to /r/bevy, and funnel forum-style Q&A to Github Discussions instead.

I a) don't want to support Reddit b) don't want to risk the history being lost forever when they go bankrupt.

**Comment by cart** [comment]
This is a hard call. Some assorted thoughts first:

1. Github discussions is a better place for Q&A. Closer to "the source" / connected to the "developer community" / next to issues (maybe saves some redundant questions), convertible to issues.
2. Github discussions is not a great place to "casually find interesting content":
    * There is no app. In practice it is a "desktop only" platform. Yes it works in mobile browsers, but I don't think many people are doing this (I certainly don't).
    * You can't aggregate "bevy" content with the other content you are interested in. This is a big one.
3. There are no established/actually used "fair ethical free range" Reddit alternatives (to my knowledge). The point of these reddit-like systems is that they can be a one stop shop for things people are interested in. If we adopt one that has no users, our community will likely have no users too. In effect, there will likely be a "reddit shaped hole" in our community for a long time.
4. Reddit's owners will eventually force open `/r/bevy` and likely boot @alice-i-cecile and I from our mod roles. When this happens new mods will be appointed and the subreddit will live on. It will likely continue to "compete" with whatever alternative we pick. If the goal is to "win" (aka move our community somewhere else), we should consider strategies to "convert" people, such as:
    1. Re-open the reddit, but leave it "locked" to new posts. Pin a post explaining the situation and directing people elsewhere. This might also trick whatever automated system is sending out these mails / we might be able to "hold on" for longer.
    2. If that strategy doesn't work for whatever reason, re-open the reddit, but continually make "redirection" posts to our new community.

**Comment by alice-i-cecile** [comment]
1. Fully agreed.
2. Agreed. Bevy Assets helps, but it's not a full solution either.
3. Kbin is starting to catch on, I'm optimistic that it'll get there but it isn't yet. Activity has been rapidly improving, but UX is still lacking. tildes.net is nice, but very small and invite-only: I don't see it ever reaching critical mass.
4. Agreed: we should push hard but limit the risk that we're completely replaced while we can.

I think your first proposal is fitting for our next step: we should wait and see if viable Reddit alternatives pop up as well.

**Comment by cart** [comment]
I've created kbin and lemmy accounts and created `/bevy` communities (might as well squat the names while we deliberate). I see no reason not to start exploring the tech.

https://kbin.social/m/bevy
https://lemmy.world/c/bevy

(I acknowledge that the lead lemmy dev is controversial and that this might affect our decision)

**Comment by cart** [comment]
I've made the subreddit "restricted" instead of "private" and stickied a post explaining the situation:
https://www.reddit.com/r/bevy/comments/14flf6m/this_subreddit_is_closed_but_the_bevy_community/

**Comment by awhillas** [comment]
Ummm, if you make it private... how will they read the stickied a post explaining the situation?

**Comment by alice-i-cecile** [comment]
It's restricted, so the linked post can be read by anyone.

**Comment by mwbryant** [comment]
As someone who makes content around Bevy (LogicProjects Youtube), the reddit was an important place for me to get the first 100 eyes on my work.  I post less there now to let others have the space (and I'm blessed with Youtube organic outreach now) but from my metrics it is an order of magnitude better than discord, twitter, or anything else I've tried, especially when first getting started.

I agree it's horrible for QA style day-to-day issues but I think it has value that will be lost if you move to less well known platforms.  Specifically I think the value comes from people just passively interested in Bevy who may have subscribed >6 months ago.  Plenty of people just casually scroll reddit and occasionally they may stumble across a showcase or video on the subreddit and these people are not actively checking other bevy specific channels.  

I know this is a niche use but I don't think I would have had the experience I've had with Bevy and probably wouldn't still be around a year later without it.  I would worry about robbing this experience from people in the future (especially those who may have more to offer the community than I do)

**Comment by kajusTheDwarf** [comment]
> As someone who makes content around Bevy (LogicProjects Youtube), the reddit was an important place for me to get the first 100 eyes on my work. I post less there now to let others have the space (and I'm blessed with Youtube organic outreach now) but from my metrics it is an order of magnitude better than discord, twitter, or anything else I've tried, especially when first getting started.
> 
> I agree it's horrible for QA style day-to-day issues but I think it has value that will be lost if you move to less well known platforms. Specifically I think the value comes from people just passively interested in Bevy who may have subscribed >6 months ago. Plenty of people just casually scroll reddit and occasionally they may stumble across a showcase or video on the subreddit and these people are not actively checking other bevy specific channels.
> 
> I know this is a niche use but I don't think I would have had the experience I've had with Bevy and probably wouldn't still be around a year later without it. I would worry about robbing this experience from people in the future (especially those who may have more to offer the community than I do)


I second this. 
The sub really helped me to get into bevy and foremost see, what it is capable of.
As much as i dislike the Reddit changes, it's still serves as a platform to reach out to people and get new people onboard.
And i'm sure the ones in charge of the changes did the math before the api change anouncement. 
So a wild guess of me would be the user loss won't be that big (but who knows).

If i may suggest something.
You could leave the sub open like before, without restriction.
In the meantime we could start to establish a community in the Fediverse (which i strongly believe will be the new "Reddit" 
in a few years)

We could advertise and link stuff from Reddit to the new platform and slowly migrate without loosing new people who otherwise wouldnt find out about bevy.

**Comment by alice-i-cecile** [comment]
Yeah, Reddit is much more valuable as an externally-facing showcase and collection of tutorials than it is as a Q&A platform.

We really don't have a good replacement set up for that yet (see Cart's point about a Reddit-shaped hole), but we *should* start building one. I agree that the Fediverse (namely kbin) seem the most promising here.

I'd like to leave the subreddit in read-only mode until the start of July at least: there's likely to be another wave as the third part apps are shut down and I'd like to hold out until then.

**Comment by alice-i-cecile** [comment]
@cart given that users can post (but generally not comment), we should just re-open instead to avoid mysteriously discouraging users.

**Comment by cart** [comment]
@alice-i-cecile Hmm its back on "comment only" instead of "post & comment" . I'm assuming I forgot to save the change. Does that change your opinion?

**Comment by alice-i-cecile** [comment]
It's better. At this point I'm concerned that the protests have faded enough to be largely ineffective. I'm okay to evaluate again after July 1st, but I think we should likely reopen with pinned messages soon. The hole is still pretty rough.

**Comment by Adhalianna** [comment]
Just wanted to add that there's also [lemmyrs.org](https://lemmyrs.org/) instance that is focused on Rust. I would expect that the interests would be a bit more aligned there. The admin seems very responsive and they keep things transparent. I think this could also be a good home for Rust-related projects.

**Comment by cart** [comment]
I've (temporarily) re-opened the subreddit: https://www.reddit.com/r/bevy/comments/14v8z0c/were_back_for_now/

**Comment by d-bucur** [comment]
My two (or 5) cents on the matter:

1. There is also the https://programming.dev/ Lemmy instance with a few active but fairly small communities. There is already a Godot community with 2k subscribers there. Issues I see with Lemmy:
- Political charge as you already mentioned
- Small community fractured over multiple instances that have zero discoverability
- Reliability of the instance: what if the admin shuts it down tomorrow? This can be mitigated by hosting a dedicated instance and having full control of it.
- UX is bad: upvoting a post on a different instance is 5 actions away. Might get better soon (see all the new shiny clients for Mastodon popping up)
- Big design flaws: https://programming.dev/comment/1076222

2. Kbin has a more centralized community with decent numbers, but doesn't seem very active in the programming area.

3. Reddit was correct in thinking the protest would be ineffective. The most optimistic estimate I've seen is traffic going [down by 6%](https://9to5mac.com/2023/06/20/reddit-usage-metrics-fall/) which is more like a 3% after checking [their source](https://www.similarweb.com/website/reddit.com/#traffic). Could be just noise from summer vacation. As much as I hate it, keeping a deal with the devil might be the best choice here.

4. Or how about a good old fashioned self hosted forum? The [Rust](https://users.rust-lang.org/) one is pretty good, although it doesn't aggregate with anything.

**Comment by alice-i-cecile** [comment]
WRT a self-hosted forum, I'm not sure that it buys us much over Github Discussions (or Discord).

**Comment by d-bucur** [comment]
GitHub Discussions is surprisingly capable, but if going forward with this route it would be better to have a separate project dedicated to QA discussions, with comprehensive categories, like on Discord, and leave the engine discussion for the engine itself. The advantage over Discord is that it is indexable by a search engine and publicly viewable.

**Comment by cart** [comment]
> WRT a self-hosted forum, I'm not sure that it buys us much over Github Discussions (or Discord).

Yeah imo anything that doesn't present a feed of new content to people in a cross-subject-area "aggregation app" that people check on a regular basis (must support both web / desktop and have iOS and Android apps) is _not_ a replacement for the reddit niche.

For "check whenever you remember to visit a bevy site explicitly", we are already very well served by Github Discussions and Discord.

**Comment by BD103** [comment]
It's been a few months, and the subreddit is back and still somewhat popular. Based on [this post by Cart](https://www.reddit.com/r/bevy/comments/14v8z0c/were_back_for_now/), can this be closed?
