### ISSUE TITLE
Web GPU Examples broken

### ISSUE THREAD

**Issue by Periosa** [bevyengine/bevy-website#693]
link 404s, similar page exists a directory above

https://github.com/bevyengine/bevy-website/blob/6c6c7cceb8a1f2fb60f37e2da0415854c9e38d59/content/news/2023-07-09-bevy-0.11/index.md?plain=1#L346
suggested fix:
```[![webgpu examples](webgpu_examples.png)](../examples-webgpu)```

**Comment by cart** [comment]
Fixed by https://github.com/bevyengine/bevy-website/commit/5dc99e370bfe57887b2ab4a02d55a17f63d246ef
