### ISSUE TITLE
0.10 -> 0.11 Error in migration guide for bevy_audio

### ISSUE THREAD

**Issue by Gnamra** [bevyengine/bevy-website#695]
In the migration guide, the following example code is given:
```rust
fn play_music(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
) {
    commands.spawn((
        AudioBundle::from_audio_source(asset_server.load("music.ogg"))
            .with_settings(PlaybackSettings::LOOP.with_volume(0.5)),
        MyMusic,
    ));
}
```

however, when I try to do this I get two errors:
- AudioBundle::from_audio_source 
no function or associated item named `from_audio_source` found for struct `AudioSourceBundle` in the current scope
function or associated item not found in `AudioSourceBundle`

- PlaybackSettings::LOOP.with_volume(0.5)
 mismatched types, expected `Volume`, found floating-point number

**Comment by IDEDARY** [comment]
Yeah, I got the same error though. So I went digging and got it working. Here is PR for [updated migration guide](https://github.com/bevyengine/bevy-website/pull/704). It solves this issue.

**Comment by IDEDARY** [comment]
The PR is merged, this can be closed.
