### ISSUE TITLE
Gamepad viewer example no longer on website

### ISSUE THREAD

**Issue by paul-hansen** [bevyengine/bevy-website#726]
The url https://bevyengine.org/examples/tools/gamepad-viewer/ used to take you to the [gamepad_viewer example](https://github.com/bevyengine/bevy/blob/e1e240709171e5a82ef9897b256fa1628d2c9d09/examples/tools/gamepad_viewer.rs)

It is also no longer listed under the tools section: https://bevyengine.org/examples/#tools

You can see it used to work here:
https://web.archive.org/web/20230322224338/https://bevyengine.org/examples/tools/gamepad-viewer/

This was a particularly valuable example for testing gamepads with Wasm, so I doubt it was removed intentionally. Would be great if we could figure out how to get it back up.

**Comment by mockersf** [comment]
It's marked as `wasm = false` here: https://github.com/bevyengine/bevy/blob/10797d4f159e8686719b32cf95eec69134b11eaa/Cargo.toml#L1310-L1318

If you can confirm it works for you, please open a PR to set it to `true`

**Comment by rparrett** [comment]
It being marked as `wasm = false` is definitely a mistake. I built it with wasm in mind and it was explicitly added to the website earlier in this PR: https://github.com/bevyengine/bevy-website/pull/486.

**Comment by rparrett** [comment]
It's back!

**Comment by paul-hansen** [comment]
Thanks for grabbing this!

Looks like the url requires a capital letter now: 
New: https://bevyengine.org/examples/Tools/gamepad-viewer/
Old: https://bevyengine.org/examples/tools/gamepad-viewer/

Not sure if that's something to be too concerned about or not. Is a slight bummer for any old links to it. I think it just changed because of how we are generating them now, probably affects other examples too.

**Comment by rparrett** [comment]
Linking a relevant discord conversation: https://discord.com/channels/691052431525675048/695741366520512563/1133883941603000361

I don't think there's an existing GH issue covering that though.
