### ISSUE TITLE
Submit Your Bevy Birthday Posts Here!

### ISSUE THREAD

**Issue by cart** [bevyengine/bevy-website#728]
As called out in my [Bevy's Third Birthday blog post](https://bevyengine.org/news/bevys-third-birthday/), I am highly encouraging everyone to write their own "Bevy Birthday" reflection posts. Just publish your post somewhere (and to social media if you want) and then link to it here. One month from now, we will do a followup "Reflecting on Bevy's Third Year" rollup post that aggregates these in one place. This is our chance as a community to celebrate our wins, identify improvement areas, and calibrate our path for the next year!

One callout: Do not criticize or critique specific community members in your posts (other than me and my actions as head of the project ... those are fair game). Critiquing specific community members is not what this platform is for and I will not give it to posts that do this. If you have constructive feedback for people, consider giving it to them personally. If that won't work, talk to our moderation team.

**Comment by nicopap** [comment]
I did a writeup here: https://devildahu.ch/devlog/bevy-3-years/

**Comment by mrtelecaster** [comment]
Not constructive feedback but [I wanted to voice my appreciation](https://twitter.com/nando_gamedev/status/1691203223380488192?s=20) for the work everyone does on Bevy, as I have just begun making a serious effort to turn my years of prototyping into games and useful libraries.

**Comment by leereilly** [comment]
🥳 Happy birthday!

https://github.blog/2023-08-25-game-bytes-august-2023

![bevy](https://github.com/bevyengine/bevy-website/assets/121322/979f91d5-772d-47e7-91ec-4640188d54e9)

**Comment by tbillington** [comment]
When are you planning to collect these @cart ?  I'm writing something at the moment, I'd forgotten about this and was reminded by alices post in discord #community 😅

**Comment by cart** [comment]
The current deadline is September 10th. If there are enough holdouts I'll consider pushing it back.

**Comment by hymm** [comment]
I wrote a bit about stageless work https://www.hsubox.design/posts/looking-back-at-stageless/

**Comment by tbillington** [comment]
Bit of a mixed bag!!

https://trent.kiwi/bevy-three-years

**Comment by alice-i-cecile** [comment]
Mine: https://www.leafwing-studios.com/blog/triage-by-controversy/

**Comment by JMS55** [comment]
Reflections on rendering - https://jms55.github.io/posts/2023-12-09-bevy-third-birthday

**Comment by cart** [comment]
Sorry for the flux, but I'm extending the deadline to end-of-day Sunday (9/17) to allow for some stragglers to write their posts.

Next year I'll be stricter about this in fairness to the people that worked to meet the deadline!

**Comment by cart** [comment]
The post is out!
https://bevyengine.org/news/community-reflection-on-bevys-third-year/
