### ISSUE TITLE
Merch Link is still live

### ISSUE THREAD

**Issue by NHodgesVFX** [bevyengine/bevy-website#730]
In the article https://bevyengine.org/news/bevys-third-birthday/ I noticed the below text

"The Rise And Fall of Bevy Merch: Haha I fortunately did not pick another low-quality merch provider. We still don't have a merch provider though. Sad!"

According to that bevy doesn't have a mercy provider however, if you go to https://merch.bevyengine.org/ there is a live merch store.

**Comment by cart** [comment]
Oops I opened it up for the Bevy Jam 3 prizes and forgot to close it back down. Fixed!
