### ISSUE TITLE
/learn/errors is unreachable

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [bevyengine/bevy-website#766]
https://bevyengine.org/learn/errors/ is not actually linked anywhere inside the website.

**Comment by SIGSTACKFAULT** [comment]
some options
- add card to /learn
- make it part of the book

**Comment by BD103** [comment]
The errors page is only linked on the [0.6 release announcement](https://github.com/bevyengine/bevy-website/blob/6ed6d8336b3da0b08bc48c08c498e1ebee76a20e/content/news/2022-01-08-bevy-0.6/index.md?plain=1#L937). I agree that it should be more accessible, likely as a card on the learn page as suggested.
