### ISSUE TITLE
Link to dev docs (for git main version of bevy)

### ISSUE THREAD

**Issue by inodentry** [bevyengine/bevy-website#775]
The API docs hosted at https://dev-docs.bevyengine.org are quite undiscoverable. I only know about them from discord discussions? I am at a new computer and tried to find the link, because I don't have it in my browser history on this machine, and I could not find it anywhere. Google only links to docs.rs when searching for bevy dev docs, the website doesn't offer any way to reach it, I had a hard time finding it via discord, ...

Please consider adding a link to it somewhere on the website (probably on the "Learn") page.

**Comment by alice-i-cecile** [comment]
They are linked in the [CONTRIBUTING.md](https://github.com/bevyengine/bevy/blob/main/CONTRIBUTING.md#writing-docs), but I wouldn't hate to see them linked in Learning too.

**Comment by inodentry** [comment]
I think the potential confusion for typical or new Bevy users can be avoided with clear wording. The website already has a link to docs.rs, clearly labeled Bevy Rust API Docs.

If we have a separate link, clearly and distinctively labeled (something like "API Docs for Pre-Release (git) Bevy"), with a description like "Documentation for developers of the Bevy engine and other bleeding-edge users.", it should be clear enough.

**Comment by mockersf** [comment]
> I think the potential confusion for typical or new Bevy users can be avoided with clear wording. The website already has a link to docs.rs, clearly labeled Bevy Rust API Docs.

Not sure clear wording is enough, we still have people use examples from git with the released version of Bevy

**Comment by BD103** [comment]
Closing as not planned. The dev-docs are more geared toward engine developers than actual users, especially since stable Bevy is mature enough that it covers most use-cases.

If anything dev-docs needs more visibility in the main repo, where developers are more likely to find it while contributing, but that's another issue.
