### ISSUE TITLE
Replace "data-driven"

### ISSUE THREAD

**Issue by quinnyo** [bevyengine/bevy-website#81]
Is Bevy "data-driven"? It says so on the website, but that's in reference to the engine's cache-optimised design / ECS, I think. If that's the case, I think that "data-oriented" is a better fit.

There is a semantic mess of confusion about what "data-driven" means. Ultimately, I don't think it's very meaningful. I think some use it to refer to game engines having the game implemented as scripts/assets, separated from the engine. In this sense, Bevy is less data-driven than other engines, considering the game code and engine code are built into one executable.

**Comment by alice-i-cecile** [comment]
Bevy is currently moderately data-driven: scenes and assets both push us in that direction. In the longer term, this will be more the case.

We should do a full pass on the marketing text; but I'm going to close this out for now.
