### ISSUE TITLE
Bevy book code should be compiled against new releases

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#83]
There have been a number of cases where the Bevy book falls out of sync from the most recent release and stays that way for a while, confusing new users that come on board right after an exciting new release.

To that end, this code should be fully compiled with Bevy as a dependency, and then its examples checked against the release candidate before the release goes live. Copy-pasting the code into test scripts is tedious, so it would be nice if this occurred more automatically.

I know mdbook supports this smoothly (because I support in [Understanding Bevy](https://github.com/alice-i-cecile/understanding-bevy)); I'm not sure that you can do the same in Zola. As an added bonus, swapping to mdbook (#47) lets end users run the example code directly if they clone this repo.

**Comment by DJMcNab** [comment]
And the actual file is https://github.com/bevyengine/bevy-website/blob/2074e3943f12b017f8792f28b29b5ea0b39a412b/static/assets/ecs.svg

**Comment by mockersf** [comment]
In my experience, Zola is great when you stay in its scope, but not very pluggable for pre- or post-processing. I don't think it would be possible to use it with compiled code without doing quite a few external scripts.

The best solution for checked code snippets is mdbook

**Comment by mockersf** [comment]
there you go: #143 😉

**Comment by alice-i-cecile** [comment]
Fixed by #281.
