### ISSUE TITLE
Fast compile instruction obsolete

### ISSUE THREAD

**Issue by Ownezx** [bevyengine/bevy-website#836]
From what I understand, the LLD linker is the default as of rust 1.70 (https://github.com/rust-lang/rust/pull/109721/). Would make what is said on https://bevyengine.org/learn/book/getting-started/setup/ obsolete?

Does does bevy recommend a previous version of rust? Should that step be done only for users that have rust <1.70?

**Comment by alice-i-cecile** [comment]
We require "latest stable at the time of the last Bevy release". So yes, now obsolete!

**Comment by QuinnPainter** [comment]
The pull request you linked only sets LLD as default for one (fairly uncommon) architecture - armv4t. I don't think modern x86-64 targets have LLD as the default yet.

**Comment by BD103** [comment]
Based on how https://github.com/rust-lang/rust/issues/39915, https://github.com/rust-lang/rust/issues/71515, and https://github.com/rust-lang/rust/issues/71520 are still open, I would say LLD is not the default yet. This issue can probably be closed for now.
