### ISSUE TITLE
Asset loading overlay stays visible after completion

### ISSUE THREAD

**Issue by purung** [bevyengine/bevy-website#841]
I couldn't find any issues related to this, which I guess is my bad since this is so obvious. Anyway, I am browsing the WebGL2 examples, and it would seem that the loading bar for the assets stays on top of the running example even after loading has completed. See screenshot below. I am on Firefox 122.0b2 (64-bit) on Windows 11, but confirmed the issue on Edge as well as Firefox on Android. 

![image](https://github.com/bevyengine/bevy-website/assets/31621019/8cff66c7-df00-4267-938f-8c6c5524a063)

**Comment by mockersf** [comment]
Fixed by #840, waiting for reviews 🙂

**Comment by purung** [comment]
Nice, great job!
