### ISSUE TITLE
Explicitly mention the usage of `default-features = false` in plugin guidelines

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#853]
I think this should explicitly mention the usage of`default-features = false` on the bevy dependency, as this could easily be forgotten.

_Originally posted by @MinerSebas in https://github.com/bevyengine/bevy-website/pull/848#discussion_r1444067234_

**Comment by TrialDragon** [comment]
Oh, I was just about to add this to the original PR; was right about to commit and push xD

**Comment by rparrett** [comment]
This is important beyond decreasing compile times lately. Any third-party plugin using Bevy's default features is preventing users from building for webgu (which requires omitting the `webgl2` feature.)

**Comment by alice-i-cecile** [comment]
> Oh, I was just about to add this to the original PR; was right about to commit and push xD

Sorry! Wasn't sure how long you'd be, so I just spun it out.
