### ISSUE TITLE
Re-order top level book sections

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy-website#858]
It feels odd to me that immediately after users learn what a `Resource` is, they are being directed to the plugin development document. IMO, a new user is going to find the "Next Steps" section much more useful at that point.

<img width="1216" alt="Screenshot 2024-01-09 at 3 36 09 PM" src="https://github.com/bevyengine/bevy-website/assets/200550/00d070e3-c4cc-4434-8162-f94b620fc45b">

I would propose that we move the plugin development section below Contributing.

**Comment by alice-i-cecile** [comment]
Totally on board with this.
