### ISSUE TITLE
Following the quick-start guide led me to a cargo compile error

### ISSUE THREAD

**Issue by jpaugh** [bevyengine/bevy-website#894]
## How can Bevy's documentation be improved?
Please have the "quick-start" mention everything I need to get started, including a link to any dependencies. Otherwise, it's a slow start, and the main Setup page would have been a quicker start.

For context, I'm brand new to Rust, and decided to try porting a medium-complexity project into Bevy for my first project&nbsp;&mdash; as one does. Also, I'm using an ancient version of Ubuntu (20.04 Focal), so that's a potential factor. However, I'm confident that even the latest Ubuntu won't install all the dependencies for me.

Below is the issue I had. I figured out how to solve it, but it shattered my expectations for a quick start.

This [Quick Start](https://bevyengine.org/learn/book/getting-started/#quick-start) didn't work for me. I got the following error when running `git checkout v0.12.1 && cargo run --example breakout`:

```
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags alsa

  The system library `alsa` required by crate `alsa-sys` was not found.
  The file `alsa.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.
```
Here's some logging context: 
[build-crash.txt](https://github.com/bevyengine/bevy/files/14076006/build-crash.txt)

Clearly, I need to install the dependencies. I believe a link to [Installing Linux Dependencies](https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md) is warranted here, to avoid new users giving up too soon.

~~Also, the Linux dependencies documentation mentions alsa-lib for Fedora, but not Ubuntu. I'm sure it's an oversight, but I'm not sure which versions of Ubuntu you want to support. For my older system (Ubuntu 20.04), I solved this issue by installing `libalsaplayer-dev`, which [exists in _some_ more recent Ubuntu releases, including Jammy, the latest LTS][some releases] but [not in the latest release, Ubuntu 22.10 Kinetic][latest-ubuntu]. I'm sure the name has simply changed.~~

Actually, it looks like the `libasound2-dev` dependency, which is mentioned in the docs, does include the right files. My "Ubuntu" instincts failed me! :-) I'm glad I found the Linux Dependencies documentation.

I'm going to check for other hidden dependencies, and update if I find any not listed on the dependencies page.

[some releases]: https://packages.ubuntu.com/search?keywords=libalsaplayer-dev&searchon=names&suite=all&section=all
[latest-ubuntu]: https://packages.ubuntu.com/search?keywords=libalsaplayer-dev&searchon=names&suite=kinetic&section=all

**Comment by alice-i-cecile** [comment]
I agree: we should eliminate the duplication in our getting started guide, and use collapsible sections instead for more complex or niche advice.

**Comment by BrunaoW** [comment]
I ran into the same problem and had a hard time searching what the hell was going on. Adding an PR that informs right below the shell snippet that executes the example.

**Comment by TrialDragon** [comment]
> I agree: we should eliminate the duplication in our getting started guide, and use collapsible sections instead for more complex or niche advice.

@alice-i-cecile to make sure I'm not misinterpreting. The preferred long term solution is to migrate the `linux_dependencies.md` content to the quick start guide where relevant, which the hyper niche content under a collapsible section (which afaik hasn't been developed here yet) to reduce duplication of resources and such, yes?

**Comment by alice-i-cecile** [comment]
I think I'd actually rather link out fully to `linux_dependencies.md`, and avoid giving any further advice on Linux dependencies in the book itself. There's a *lot* of OS's there, and unless we have something even better than a collapsible section I'd prefer to keep it out of the book.
