### ISSUE TITLE
The new book isn't correctly hiding code behind `#`

### ISSUE THREAD

**Issue by 13ros27** [bevyengine/bevy-website#911]
The new [book](https://bevyengine.org/learn/book/ecs/entities-components/) isn't correctly hiding code in examples that is hidden behind a `#`. This should act like [rustdoc](https://doc.rust-lang.org/beta/rustdoc/write-documentation/documentation-tests.html#hiding-portions-of-the-example), however currently:
![image](https://github.com/bevyengine/bevy-website/assets/32036861/4aeb604d-7ea0-4bc0-8c8a-4e0b6960246c)

**Comment by hymm** [comment]
zola doesn't support `#`. You need to use skip_lines on the triple backtick line of the code block.

```
  ```rust,hide_lines=1-2 6-8
```

**Comment by TrialDragon** [comment]
Shoot We're supposed to use the utility tool introduced in #405 to convert those into zola annotations afaik.

**Comment by TrialDragon** [comment]
Ditto for the quick start guide where it is commenting out the Bevy prelude use boilerplate. (Tho that means minor modification to the start script of the tool to have it run on quick-start too I believe).

**Comment by BD103** [comment]
Was this closed by #915?

**Comment by 13ros27** [comment]
I don't know when the website rebuilds, is it after every merge? But if it has rebuilt then I'm still seeing this issue.

**Comment by TrialDragon** [comment]
> Was this closed by #915?

No. That was a PR to fix a bug in the tool useful to generate the proper hidelines for comments. It wasn't the actual generation of the stuff needed to hide lines.

Given this is effecting the public-facing site thru quick-start I'll fix it tonight. Shouldn't be more than a few minor changes and a run to get it done.
