### ISSUE TITLE
Broken documentation links from tutorial

### ISSUE THREAD

**Issue by sciguy16** [bevyengine/bevy-website#97]
The documentation links for Rust types from the Getting Started guide are broken - for example on the [ECS page](https://bevyengine.org/learn/book/getting-started/ecs/) the link for `System` points to `https://docs.rs/bevy_ecs/std/bevy_ecs/trait.System.html`, which doesn't exist on docs.rs.

The link works if `std` is replaced with `0.4.0` or `latest` (e.g. https://docs.rs/bevy_ecs/0.4.0/bevy_ecs/trait.System.html)

![image](https://user-images.githubusercontent.com/10563148/107990569-96dcdb00-6fcc-11eb-8944-966a5b9c0e46.png)

**Comment by TimJentzsch** [comment]
I believe this can be closed, at least on the ECS page all links seem to be working now.
