### ISSUE TITLE
Proper aside info / note blocks

### ISSUE THREAD

**Issue by TrialDragon** [bevyengine/bevy-website#976]
It would be nice to have proper info blocks / call outs / note blocks / asides for use in the book and articles. I believe semantically this should be an `aside` element.

Would see use as replacing all the `**Note**:`'s in the book; also useful for the to-do short-code style-wise.

Relevant comment: https://github.com/bevyengine/bevy-website/pull/886#discussion_r1462100753

**Comment by SIGSTACKFAULT** [comment]
Previous Work: ReStructuredText calls these *admonitions*. https://docutils.sourceforge.io/docs/ref/rst/directives.html#admonitions

**Comment by TrialDragon** [comment]
Added in #1167 .
