### ISSUE TITLE
Migration Guide 0.13 - "Unload render assets from RAM" is outdated

### ISSUE THREAD

**Issue by afonsolage** [bevyengine/bevy-website#984]
[Unload render assets from RAM](https://github.com/bevyengine/bevy/pull/10520) migration guide is outdated due to [RenderAssetPersistencePolicy → RenderAssetUsages](https://github.com/bevyengine/bevy/pull/11399).

I could just make a PR to replace `RenderAssetPersistencePolicy::Keep` with `RenderAssetUsage::MAIN_WORLD | RenderAssetUsage::RENDER_WORLD` as per #11399, but I don't know if it will make sense:

---

- Asset loaders (GLTF, etc) now load meshes and textures without `cpu_persistent_access`. These assets will be removed from `Assets<Mesh>` and `Assets<Image>` once `RenderAssets<Mesh>` and `RenderAssets<Image>` contain the GPU versions of these assets, in order to reduce memory usage. If you require access to the asset data from the CPU in future frames after the GLTF asset has been loaded, modify all dependent `Mesh` and `Image` assets and set `cpu_persistent_access` to `RenderAssetUsage::MAIN_WORLD | RenderAssetUsage::RENDER_WORLD`.
- `Mesh` now requires a new `cpu_persistent_access` field. Set it to `RenderAssetUsage::MAIN_WORLD | RenderAssetUsage::RENDER_WORLD` to mimic the previous behavior.
- `Image` now requires a new `cpu_persistent_access` field. Set it to `RenderAssetUsage::MAIN_WORLD | RenderAssetUsage::RENDER_WORLD` to mimic the previous behavior.
- `MorphTargetImage::new()` now requires a new `cpu_persistent_access` parameter. Set it to `RenderAssetUsage::MAIN_WORLD | RenderAssetUsage::RENDER_WORLD` to mimic the previous behavior.
- `DynamicTextureAtlasBuilder::add_texture()` now requires that the `TextureAtlas` you pass has an `Image` with `cpu_persistent_access: RenderAssetUsage::MAIN_WORLD | RenderAssetUsage::RENDER_WORLD`. Ensure you construct the image properly for the texture atlas.
- The `RenderAsset` trait has significantly changed, and requires adapting your existing implementations.
- The trait now requires `Clone`.
- The `ExtractedAsset` associated type has been removed (the type itself is now extracted).
- The signature of `prepare_asset()` is slightly different
- A new `persistence_policy()` method is now required (return `RenderAssetUsage::RENDER_WORLD` to match the previous behavior).

**Comment by rparrett** [comment]
> I could just make a PR to replace RenderAssetPersistencePolicy::Keep with RenderAssetUsage::MAIN_WORLD | RenderAssetUsage::RENDER_WORLD as per #11399, but I don't know if it will make sense:

That is `RenderAssetUsage::default()` since https://github.com/bevyengine/bevy/pull/11212.

**Comment by brianreavis** [comment]
Just a note: it's `RenderAssetUsages`, not `RenderAssetUsage`.

Also, the `cpu_persistent_access` fields are now `asset_usage`, and the `persistence_policy()` method is now `asset_usage()`.

**Comment by afonsolage** [comment]
#987

**Comment by afonsolage** [comment]
Fixed on #987

**Comment by alice-i-cecile** [comment]
This fix was made to a branch, not to `main`, so needs to be redone.
